---
title: "R Notebook"
---

# Library

```{r}
library(tidyverse)
library(SingleCellExperiment)
library(lemur)
library(SpatialExperiment)
library(patchwork)

library(boot)
library(tidyr) 
library(splineTimeR)
library(glue)
library(qs)
library(plotly)


```

```{r}
source("../../src/util.R")
source("../../config/config.R")
```

# Load data

```{r}
res.dir <- get.res.dir()
res.dir.LEMUR <- file.path(res.dir, "LEMUR")
fit_all <- qs::qread(file.path(res.dir.LEMUR, "fit.qs"))
nei_all <- qs::qread(file.path(res.dir.LEMUR, "nei.qs"))
spe <- qs::qread(file.path(res.dir.LEMUR, "se_dist.qs"))

nei <- nei_all
head(nei)

marker.sel <- "VWF&PECAM1"
target.cell <- "ECs"
```

# Bootstrap for mean

```{r}
all.genes <- nei$name

# to get variable genes
num_genes <- 1000
genes_of_interest <- spe@metadata$var.genes %>% sample(num_genes)

if (!"THY1" %in% genes_of_interest) {
  genes_of_interest <- c(genes_of_interest, "THY1")
}
# length(filter(nei, name == genes_of_interest)$neighborhood[[1]])
```

```{r}
# length(sce.pseudo$dist.cluster)
mean_stat <- function(data, indices) {
  return(mean(data[indices], na.rm = TRUE))
}

# Function to perform bootstrapping and add orig and expr columns
# TODO : refactor; check samples in each cluster
perform_bootstrapping <- function(origin, genes_of_interest, gene_id) {
  
  # mask for if a spot is in neighborhood
  mask <- matrix(NA, nrow = length(genes_of_interest), ncol = ncol(fit_all), 
                 dimnames = list(genes_of_interest, colnames(fit_all)))
  
  mask2 <- matrix(1, nrow = length(genes_of_interest), ncol = ncol(fit_all), 
                 dimnames = list(genes_of_interest, colnames(fit_all)))
  
  for(id in genes_of_interest){
    mask[id, filter(nei, name == id)$neighborhood[[1]]] <- 1
    mask2[id, filter(nei, name == id)$neighborhood[[1]]] <- NA
  }


  # construct two assays: inside and outside
  sce.pseudo <- SingleCellExperiment(
    list(inside = as.matrix(logcounts(fit_all)[genes_of_interest,,drop=FALSE] * mask),
    outside = as.matrix(logcounts(fit_all)[genes_of_interest,,drop=FALSE] * mask2)
    ),
    colData = as.data.frame(colData(fit_all))
    )
 
  res <- tibble(expr = as.data.frame(assay(sce.pseudo, origin)[gene_id,])) %>% 
    mutate(dist.cluster = sce.pseudo$dist.cluster) %>% 
    group_by(dist.cluster) %>% 
    do({
      cluster <- unique(.$dist.cluster) %>% as.character()
      R <-  500
      # remove NA before sampling
      data <- .$expr[!is.na(.$expr)]
      
      # no data in a cluster
      if (length(data) == 0) {
        data.frame(
          expr = rep(0, R), 
          n = nrow(.), 
          lower = NA, 
          upper = NA, 
          SampleName = rep(glue("{origin}_{gene_id}_{cluster}"), R),
          dist.cluster.1 = cluster,
          Replicate = seq(R)
        )
      }else{
        boot.res <- boot(data, statistic = mean_stat, R = R)
        ci <- boot.ci(boot.res, conf = c(0.95), type = c('perc'))
        lower <-  ci$percent[4]
        upper <-  ci$percent[5]
        
        if (length(lower) == 0) {
          lower <-  NA
          upper <-  NA
        }
        data.frame(
          expr = boot.res$t, 
          n = nrow(.), 
          lower = lower, 
          upper = upper, 
          SampleName = rep(glue("{origin}_{gene_id}_{cluster}"), R),
          dist.cluster.1 = cluster,
          Replicate = seq(R)
          )
      }
    }) %>% 
    ungroup() %>%
    mutate(origin = origin, symbol = gene_id)
  
  return(res)
}


# perform_bootstrapping("inside", genes_of_interest, gene_id)
# 
# comparison_data <- bind_rows(
#       perform_bootstrapping("inside", genes_of_interest),
#       perform_bootstrapping("outside", genes_of_interest)
#     )
```

# Plot all curves

```{r}
rerun.boot <- F

# bootstrap for all selected genes
if (rerun.boot) {
  expression_data <- list()
  boot.res <- list()
  for(id in genes_of_interest){
    # perform bootstrapping for both "inside" of genes
    res_inside <- perform_bootstrapping("inside", genes_of_interest, id)
    
    expression_data[[id]] <- res_inside$expr
    boot.res[[id]] <- res_inside
    # rep(c(id, id_target), each = mid)
  }
      
  qsave(boot.res, file.path(res.dir, glue("boot_res_nei_{num_genes}.qs")))
  qsave(expression_data, file.path(res.dir, glue("expression_data_nei_{num_genes}.qs")))
  qsave(res_inside, file.path(res.dir, glue("comparison_data_nei_{num_genes}.qs")))
}
```

```{r}
num_genes <- 500
expression_data <- qread(file.path(res.dir, glue("expression_data_nei_{num_genes}.qs")))
info <- qread(file.path(res.dir, glue("comparison_data_nei_{num_genes}.qs")))
boot.res <- qread(file.path(res.dir, glue("boot_res_nei_{num_genes}.qs")))

```

```{r}
# shift all the curves down by their mean
expression_data_shifted <- lapply(expression_data, function(x) x - mean(x))
names(expression_data_shifted) <- names(expression_data)
```

```{r}
num.genes <- length(expression_data_shifted)
gene_ids <- rep(names(expression_data_shifted), each = length(expression_data_shifted[[1]]))
avg.dists <- lapply(as.character(info$dist.cluster), calculate.avg.dist) %>%
  unlist() %>%
  rep(., num.genes) %>%
  unlist()

# concatenate the lists to one list
comparison_data <- do.call(c, expression_data_shifted)

# set y limits
y_min <- min(comparison_data)
y_max <- max(comparison_data)
# y_min <- -1
# y_max <- 5
y_expansion <- 0.6
# degree of freedom of natural cubic spline 
df <- 5

expr_comparison_pl <- tibble(expr = comparison_data) %>%
  mutate(avg.dist = as.factor(avg.dists), gene = as.factor(gene_ids)) %>% 
  ggplot(aes(x = avg.dist, y = expr, text = gene)) +
    # geom_point(aes(color = gene), size = 1, alpha = 0) +
    # geom_boxplot(aes(color = gene), width = 0.3, outlier.shape = NA) +  # Add boxplot
    geom_smooth(aes(color = gene, x = as.numeric(avg.dist), y = expr), method = 'lm', formula = y ~ ns(x, df = df), se = FALSE, linewidth = 0.13) +
    # geom_errorbar(aes(ymin = lower, ymax = upper, color = origin), width = 0.8, alpha = 0.5) +
    scale_color_manual(values = rep("grey", length(unique(gene_ids)))) +
    scale_x_continuous(breaks = unique(avg.dists), labels = unique(avg.dists)) +  # Ensure all x-axis values are shown
    scale_y_continuous(limits = c(y_min, y_max), expand = expansion(add = y_expansion)) +
    guides(x = guide_axis(angle = 45)) +
    theme(legend.position = "none") +
    labs(color = "", y = "Expression (log transformed)", x = 'average dist./spots',
         subtitle = paste0("All exprs. vs. Dist to endothelial cell annot. by ", marker.sel, " - bootstrapped "))  +
    theme(plot.subtitle = element_text(size = 7))
    # annotate("text", x = Inf, y = Inf, label = glue("P.Val = {P.Val}"), hjust = 1.1, vjust = 1.5, size = 3) +
    #guides(color = guide_legend(override.aes = list(linetype = 1, size = 2)))  # Set legend as lines

# TODO: Save the plot with rectangular dimensions
# expr_comparison_pl
```

```{r}
# hover up to hightlight line and gene name
expr_comparison_pl_interactive <- ggplotly(expr_comparison_pl, tooltip = "text")
expr_comparison_pl_interactive
```

```{r}
# extract median
extract_median <- function(res) {
  medians <- res %>% 
    group_by(dist.cluster) %>% 
    summarize(median_expr = median(expr, na.rm = TRUE)) %>% 
    ungroup() %>% 
    pull(median_expr) # get it as a vector
  return(medians)
}

gene_medians <- lapply(boot.res, extract_median) %>% 
  do.call(rbind, .)

# shift all the curves down by their mean
gene_medians_centered <- gene_medians - rowMeans(gene_medians)

# calculate the slope for the fist segment
avg.dists.unique <- lapply(as.character(boot.res[[1]]$dist.cluster), calculate.avg.dist) %>% unique(.) %>% unlist()

x_dist <- avg.dists.unique[2] - avg.dists.unique[1]
slopes <- (gene_medians_centered[,2] - gene_medians_centered[,1]) / x_dist 

hist_result <- hist(slopes, plot = F)
```

```{r}
plot(hist_result)

# hist_result$breaks
slope_upper <- 0.2
slope_lower <- -slope_upper
```

```{r}
genes_incr <- slopes[slopes > slope_upper] %>% names()
genes_decr <- slopes[slopes < slope_lower] %>% names()
genes_flat <- setdiff(names(slopes), c(genes_incr, genes_decr))

length(genes_flat)
length(genes_decr)
length(genes_incr)
```

```{r}
genes_plot <- genes_flat
genes_plot <- genes_decr
genes_plot <- genes_incr
```

```{r}
marker.genes <- qread(file.path(res.dir, "markers.qs"))
table(marker.genes$cluster)

markers <- marker.genes %>% 
              group_by(cluster) %>%
              # top_n(n = 100, wt = avg_log2FC) %>% 
              filter(pct.1 > 0.25 & pct.2 >= 0) %>% 
              summarize(gene_list = list(gene)) %>%   # Create a list of genes for each cluster
              deframe()     
length(markers)
```

```{r}
markers_to_ctypes <- vector("list", length(genes_of_interest))  # Create an empty list
names(markers_to_ctypes) <- genes_of_interest 

for (gene in genes_of_interest) {
  mask <- sapply(markers, function(x) gene %in% x ) # sapply simplify res as vector
  markers_to_ctypes[[gene]] <- names(markers)[mask]
}
markers_to_ctypes[genes_incr] %>% unlist() %>% unique()
```

```{r}
expr_comparison_pl <- tibble(expr = comparison_data) %>%
  mutate(avg.dist = as.factor(avg.dists), 
         gene = as.factor(gene_ids), 
         ctypes = sapply(gene,  function(g) paste(markers_to_ctypes[[g]], collapse = ", ")),
         hover_text = paste0("Gene: ", gene, 
                             "<br>marker.of: ", ctypes)) %>% 
  
  filter(gene %in% genes_plot) %>% 
  ggplot(aes(x = avg.dist, y = expr, text = hover_text)) +
    # geom_point(aes(color = gene), size = 1, alpha = 0) +
    # geom_boxplot(aes(color = gene), width = 0.3, outlier.shape = NA) +  # Add boxplot
    geom_smooth(aes(color = gene, x = as.numeric(avg.dist), y = expr), method = 'lm', formula = y ~ ns(x, df = df), se = FALSE, linewidth = 0.13) +
    # geom_errorbar(aes(ymin = lower, ymax = upper, color = origin), width = 0.8, alpha = 0.5) +
    scale_color_manual(values = rep("grey", length(unique(gene_ids)))) +
    scale_x_continuous(breaks = unique(avg.dists), labels = unique(avg.dists)) +  # Ensure all x-axis values are shown
    scale_y_continuous(limits = c(y_min, y_max), expand = expansion(add = y_expansion)) +
    guides(x = guide_axis(angle = 45)) +
    theme(legend.position = "none") +
    labs(color = "", y = "Expression (log transformed)", x = 'average dist./spots',
         subtitle = paste0("All exprs. vs. Dist to endothelial cell annot. by ", marker.sel, " - bootstrapped "))  +
    theme(plot.subtitle = element_text(size = 7))
    # annotate("text", x = Inf, y = Inf, label = glue("P.Val = {P.Val}"), hjust = 1.1, vjust = 1.5, size = 3) +
    #guides(color = guide_legend(override.aes = list(linetype = 1, size = 2)))  # Set legend as lines

# hover up to hightlight line and gene name
expr_comparison_pl_interactive <- ggplotly(expr_comparison_pl, tooltip = "text")
expr_comparison_pl_interactive
```

# Cluster curves by PCA

```{r}
pca_result <- prcomp(gene_medians, center = F, scale. = F)

# Get the reduced dimensions (principal components)
pca_reduced <- pca_result$x
```

# splineTime R

```{r}
# bootstrap for THY1
id_target <- "THY1"

if (rerun.boot) {
  res_outside <- perform_bootstrapping("inside", genes_of_interest, id_target)
  mid <- nrow(comparison_data) / 2
  
  expression_data <- list()
  for(id in genes_of_interest){
    # perform bootstrapping for both "inside" of genes
    res_inside <- perform_bootstrapping("inside", genes_of_interest, id)
    
    comparison_data <- bind_rows(
        res_inside,
        res_outside
    )
    
    expression_data[[id]] <- comparison_data$expr
    # rep(c(id, id_target), each = mid)
  }
      
  qsave(expression_data, file.path(res.dir, glue("expression_data_spline_{num_genes}.qs")))
  qsave(comparison_data, file.path(res.dir, glue("comparison_data_spline_{num_genes}.qs")))
}
```

## difference between nei of different genes

```{r}
expression_data <- qread(file.path(res.dir, glue("expression_data_spline_{num_genes}.qs")))
comparison_data <- qread(file.path(res.dir, glue("comparison_data_spline_{num_genes}.qs")))
genes_of_interest <- names(expression_data)

# code dist.cluster as numeric
nUnique <- levels(comparison_data$dist.cluster) %>% length()

phenoData <-  data.frame(
  SampleName = rep(c("gene_compared", id_target), each = mid),
  Time = as.integer(comparison_data$dist.cluster),
  Treatment = rep(c("gene_compared", id_target), each = mid),
  Replicate = comparison_data$Replicate
) %>% as(., "AnnotatedDataFrame")


expression_data <- do.call(rbind, expression_data)
rownames(expression_data) <- genes_of_interest
dim(expression_data)

featureData <-  data.frame(genes = genes_of_interest) %>% as("AnnotatedDataFrame")
rownames(featureData) <- genes_of_interest
featureData

expression_set <- ExpressionSet(
  assayData = expression_data,
  phenoData = phenoData,
  featureData = featureData
)

df <- 3
diffExprs <- splineDiffExprs(eSetObject = expression_set, 
                             df = df,
                             # cutoff.adj.pVal = 0.01, 
                             reference = id_target,
                             intercept = FALSE)

p.vals <- diffExprs$P.Value
adj.p.Val <- diffExprs$adj.P.Val

names(p.vals) <- diffExprs$genes

p.vals.sort <- sort(p.vals, decreasing = T) %>% signif(3)
p.vals.sort[1:10]
head(p.vals.sort, 10)
genes_sel <- head(p.vals.sort, 10) %>% names()
genes_sel

qsave(diffExprs, file.path(res.dir, glue("diffExprs_spline_{num_genes}.qs")))
```

```{r}
splinePlot(eSetObject = expression_set,
           df = df,
           reference = id_target,
           toPlot = genes_sel
           )
```

# Misc.

```{r}
# Create a list
my_list <- list(1, 2, 3)

# Repeat the list 3 times
repeated_list <- rep(my_list, 3) %>% unlist()

# Print the repeated list
print(repeated_list)

```

```         
```
