---
title: "Test"
output:
  html_document:
    df_print: paged
output.width: "75%"
---

# Library

```{r}
library(Matrix)
library(ggplot2)
library(gghighlight)
library(tidyverse)

library(STdeconvolve)
library(lemur)
library(igraph)

```

```{r}
source("../src/util.R")
```

```{r}
# coords generated from chatGPT
coords <- matrix(c(
  0, 0, 1, 0, 2, 0,
  0, 1, 1, 1, 2, 1,
  0, 2, 1, 2, 2, 2
), ncol = 2, byrow = TRUE)

```

```{r}
adjacency.matrix <- get.adjacency.matrix(coords, squared.radius = 2.5)
sum(adjacency.matrix)

# build a graph
g <- graph_from_adjacency_matrix(adjacency.matrix, mode = 'undirected')

g <- add_vertices(g, 3)
g <- add_edges(g, edges = c(10, 11))

# color target vertices
to <- c(2, 4, 10)
for (v in to) {
  V(g)[v]$color <- 'blue'
}

plot(g)
components(g)
plot(g, vertex.label = V(g)$label, vertex.color = V(g)$color)

```

```{r}
from <- 1:12
from
to
min.dists.mat <- get.all.dists(g, from, to)
weights <- rep(1, ncol(min.dists.mat))
get.min.dists(min.dists.mat, weights)


```
