---
title: "R Notebook"
---

# Library

```{r}
library(tidyverse)
library(SingleCellExperiment)
library(lemur)
library(SpatialExperiment)
library(patchwork)

library(boot)
library(tidyr) 
library(splineTimeR)
library(glue)
# library(assertthat)
library(qs)


```

```{r}
source("../src/util.R")
source("../config/config.R")
```

# Load data

```{r}
res.dir <- get.res.dir()
res.dir.LEMUR <- file.path(res.dir, "LEMUR")
fit_all <- qs::qread(file.path(res.dir.LEMUR, "fit.qs"))
nei_all <- qs::qread(file.path(res.dir.LEMUR, "nei.qs"))
spe <- qs::qread(file.path(res.dir.LEMUR, "se_dist.qs"))

nei <- nei_all
head(nei)

marker.sel <- "VWF&PECAM1"
target.cell <- "ECs"
```

# Bootstrap for mean

```{r}
all.genes <- nei$name

# to get variable genes
set.seed(1)
num_genes <- 500
genes_of_interest <- c('THY1', 'PECAM1')
genes_of_interest <- c(spe@metadata$var.genes %>% sample(num_genes))
# genes_of_interest
# length(filter(nei, name == genes_of_interest)$neighborhood[[1]])
```

```{r}
# length(sce.pseudo$dist.cluster)
mean_stat <- function(data, indices) {
  return(mean(data[indices], na.rm = TRUE))
}

# Function to perform bootstrapping and add orig and expr columns
# TODO : refactor; check samples in each cluster
perform_bootstrapping <- function(origin, genes_of_interest, gene_id) {
  
  # mask for if a spot is in neighborhood
  mask <- matrix(NA, nrow = length(genes_of_interest), ncol = ncol(fit_all), 
                 dimnames = list(genes_of_interest, colnames(fit_all)))
  
  mask2 <- matrix(1, nrow = length(genes_of_interest), ncol = ncol(fit_all), 
                 dimnames = list(genes_of_interest, colnames(fit_all)))
  
  for(id in genes_of_interest){
    mask[id, filter(nei, name == id)$neighborhood[[1]]] <- 1
    mask2[id, filter(nei, name == id)$neighborhood[[1]]] <- NA
  }


  # construct two assays: inside and outside
  sce.pseudo <- SingleCellExperiment(
    list(inside = as.matrix(logcounts(fit_all)[genes_of_interest,,drop=FALSE] * mask),
    outside = as.matrix(logcounts(fit_all)[genes_of_interest,,drop=FALSE] * mask2)
    ),
    colData = as.data.frame(colData(fit_all))
    )
 
  res <- tibble(expr = as.data.frame(assay(sce.pseudo, origin)[gene_id,])) %>% 
    mutate(dist.cluster = sce.pseudo$dist.cluster) %>% 
    group_by(dist.cluster) %>% 
    do({
      cluster <- unique(.$dist.cluster) %>% as.character()
      R <-  1000
      # remove NA before sampling
      data <- .$expr[!is.na(.$expr)]
      
      # no data in a cluster
      if (length(data) == 0) {
        data.frame(
        expr = rep(0, 1000), 
        n = nrow(.), 
        lower = NA, 
        upper = NA, 
        SampleName = rep(glue("{origin}_{gene_id}_{cluster}"), R),
        Replicate = seq(R)
        )
      }else{
        boot.res <- boot(data, statistic = mean_stat, R = R)
        ci <- boot.ci(boot.res, conf = c(0.95), type = c('perc'))
        lower <-  ci$percent[4]
        upper <-  ci$percent[5]
        
        if (length(lower) == 0) {
          lower <-  NA
          upper <-  NA
        }
        data.frame(
          expr = boot.res$t, 
          n = nrow(.), 
          lower = lower, 
          upper = upper, 
          SampleName = rep(glue("{origin}_{gene_id}_{cluster}"), R),
          Replicate = seq(R)
          )
      }
    }) %>% 
    ungroup() %>%
    mutate(origin = origin, symbol = gene_id)
  
  return(res)
}


# perform_bootstrapping("inside", genes_of_interest, gene_id)
# 
# comparison_data <- bind_rows(
#       perform_bootstrapping("inside", genes_of_interest),
#       perform_bootstrapping("outside", genes_of_interest)
#     )
```

# splineTime R

## difference between nei and outside neighborhood

```{r}
# Perform bootstrapping for both "inside" and "outside"
expression_data <- list()
for(id in genes_of_interest){
  res_inside <- perform_bootstrapping("inside", genes_of_interest, id)
  res_outside <- perform_bootstrapping("outside", genes_of_interest, id)
  
  comparison_data <- bind_rows(
      res_inside,
      res_outside
  )
  
  expression_data[[id]] <- comparison_data$expr
    
}

# code dist.cluster as numeric
nUnique <- levels(comparison_data$dist.cluster) %>% length()

phenoData <-  data.frame(
  SampleName = comparison_data$SampleName,
  Time = as.integer(comparison_data$dist.cluster),
  Treatment = comparison_data$origin,
  Replicate = comparison_data$Replicate
) %>% as(., "AnnotatedDataFrame")

expression_data <- do.call(rbind, expression_data)
rownames(expression_data) <- genes_of_interest
dim(expression_data)

featureData <-  data.frame(genes = genes_of_interest) %>% as("AnnotatedDataFrame")
rownames(featureData) <- genes_of_interest
featureData
```

```{r}
# sum(!is.finite(expression_data))
qsave(expression_data, file.path(res.dir, glue("expression_data_spline_{num_genes}.qs")))
```

```{r}
expression_set <- ExpressionSet(
  assayData = expression_data,
  phenoData = phenoData,
  featureData = featureData
)
```

```{r}
diffExprs <- splineDiffExprs(eSetObject = expression_set, df = 3,
                             cutoff.adj.pVal = 0.01, reference = "outside",
                              intercept = FALSE)

top_genes <- diffExprs$genes[num_genes]
head(diffExprs)
top_genes
diffExprs$P.Value[num_genes]
```

```{r}
qsave(diffExprs, file.path(res.dir, glue("diffExprs_spline_{num_genes}.qs")))
```

```{r}
splinePlot(eSetObject = expression_set, df = 3,
            reference = "outside", toPlot = top_genes)
```

## difference between nei of different genes

```{r}
# bootstrap for THY1
id_target <- "THY1"
res_outside <- perform_bootstrapping("inside", genes_of_interest, id_target)
mid <- nrow(comparison_data) / 2

expression_data <- list()
for(id in genes_of_interest){
  # perform bootstrapping for both "inside" of genes
  res_inside <- perform_bootstrapping("inside", genes_of_interest, id)
  
  comparison_data <- bind_rows(
      res_inside,
      res_outside
  )
  
  expression_data[[id]] <- comparison_data$expr
  # rep(c(id, id_target), each = mid)
}
    
qsave(expression_data, file.path(res.dir, glue("expression_data_spline_{num_genes}.qs")))
qsave(comparison_data, file.path(res.dir, glue("comparison_data_spline_{num_genes}.qs")))
```

```{r}
expression_data <- qread(file.path(res.dir, glue("expression_data_spline_{num_genes}.qs")))
comparison_data <- qread(file.path(res.dir, glue("comparison_data_spline_{num_genes}.qs")))
genes_of_interest <- names(expression_data)

# code dist.cluster as numeric
nUnique <- levels(comparison_data$dist.cluster) %>% length()

phenoData <-  data.frame(
  SampleName = rep(c("gene_compared", id_target), each = mid),
  Time = as.integer(comparison_data$dist.cluster),
  Treatment = rep(c("gene_compared", id_target), each = mid),
  Replicate = comparison_data$Replicate
) %>% as(., "AnnotatedDataFrame")



expression_data <- do.call(rbind, expression_data)
rownames(expression_data) <- genes_of_interest
dim(expression_data)

featureData <-  data.frame(genes = genes_of_interest) %>% as("AnnotatedDataFrame")
rownames(featureData) <- genes_of_interest
featureData

expression_set <- ExpressionSet(
  assayData = expression_data,
  phenoData = phenoData,
  featureData = featureData
)

df <- 3
diffExprs <- splineDiffExprs(eSetObject = expression_set, 
                             df = df,
                             # cutoff.adj.pVal = 0.01, 
                             reference = id_target,
                             intercept = FALSE)

p.vals <- diffExprs$P.Value
adj.p.Val <- diffExprs$adj.P.Val

names(p.vals) <- diffExprs$genes

p.vals.sort <- sort(p.vals, decreasing = T) %>% signif(3)
p.vals.sort[1:10]
head(p.vals.sort, 10)
genes_sel <- head(p.vals.sort, 10) %>% names()
genes_sel

qsave(diffExprs, file.path(res.dir, glue("diffExprs_spline_{num_genes}.qs")))
```

```{r}
splinePlot(eSetObject = expression_set,
           df = df,
           reference = id_target,
           toPlot = genes_sel
           )
```

# Misc.

```         
```
