---
title: "R Notebook"
---

# Library

```{r}
library(tidyverse)
library(SingleCellExperiment)
library(lemur)
library(SpatialExperiment)
library(gghighlight)
library(patchwork)

library(boot)
```

```{r}
source("../src/util.R")
source("../config/config.R")
```

# Load data

```{r}
res.dir <- file.path(get.res.dir(), "LEMUR")
fit <- qs::qread(file.path(res.dir, "fit_small.qs"))
nei <- qs::qread(file.path(res.dir, "nei_small.qs"))
spe <- qs::qread(file.path(res.dir, "se_dist.qs"))


```

# Analysis

```{r}
gene_of_interest <- nei$name[2] # NOC2L
gene_of_interest <- nei$name[1] # THY1
gene_of_interest
```

## Dist plot of all pixels

```{r}
expr <-  counts(spe)[gene_of_interest,]
expr <- as.data.frame(expr)
expr <- as.numeric(unlist(expr))
table(expr)

expr_comparison_scatter <- as_tibble(colData(spe)) %>%
  mutate(dist.cluster = ordered(dist.cluster, levels = levels(spe$dist.cluster))) %>%
  mutate(expr = expr) %>%
  filter(!is.null(expr)) %>% 
  ggplot(aes(x = dist.cluster, y = expr, fill = dist.cluster)) +
    geom_violin(trim = FALSE) +
    # scale_y_continuous(limits = c(0, 10), expand = expansion(add = 0)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression",
         subtitle = paste0("All pixels - ", " expr. vs. Dist to endothelial cell"))  +
    theme(plot.subtitle = element_text(size = 7))

expr_comparison_scatter
```

```{r}
res.dir <- get.res.dir()
filename <- paste0("Violin plot of dists",  ".png")
ggsave(filename = file.path(res.dir, "plots", filename), plot = expr_comparison_scatter, device = "png", width = 10, height = 8, dpi = 500)
```

```{r}
expr <-  counts(spe)[gene_of_interest,]
expr <- as.data.frame(expr)
expr <- as.numeric(unlist(expr))
table(expr)

expr_comparison_scatter <- as_tibble(colData(spe)) %>%
  mutate(dist.cluster = ordered(dist.cluster, levels = levels(spe$dist.cluster))) %>%
  mutate(expr = expr) %>%
  filter(!is.null(expr)) %>% 
  ggplot(aes(x = dist.cluster, y = expr, fill = dist.cluster)) +
    geom_boxplot(alpha = 0.3) + # Add boxplots for reference
    stat_summary(
      fun = function(x) quantile(x, probs = 0.75), 
      geom = "point", 
      shape = 23, 
      size = 3, 
      fill = "red", 
      color = "black"
    ) + 
    scale_y_continuous(limits = c(0, 20), expand = expansion(add = 0)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression",
         subtitle = paste0("All pixels - ", " expr. vs. Dist to endothelial cell"))  +
    theme(plot.subtitle = element_text(size = 7))

expr_comparison_scatter
```

```{r}
expr <-  counts(spe)[gene_of_interest,]
expr <- as.data.frame(expr)
expr <- as.numeric(unlist(expr))
table(expr)

expr_comparison_scatter <- as_tibble(colData(spe)) %>%
  mutate(expr = expr) %>%
  ggplot(aes(x = min.dists, y = expr)) +
    geom_point(size = 1) +
    scale_y_continuous(limits = c(0, 20), expand = expansion(add = 0)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression",
         subtitle = paste0("All pixels - ", " expr. vs. Dist to endothelial cell"))  +
    theme(plot.subtitle = element_text(size = 7))

expr_comparison_scatter
```

## Dist Clusters in UMAP

```{r}
set.seed(1)
umap <- uwot::umap(t(fit$embedding))
```

```{r}
as_tibble(colData(fit)) %>%
  mutate(umap = umap) %>%
  ggplot(aes(x = umap[,1], y = umap[,2])) +
    geom_point(aes(color = dist.cluster), size = 0.7, stroke = 0) +
    guides(color = guide_legend(override.aes = list(size = 1)))
```

## Correlation plot

### Norm case

```{r, paged.print=FALSE}

mask <- matrix(NA, nrow = length(gene_of_interest), ncol = ncol(fit), 
               dimnames = list(gene_of_interest, colnames(fit)))
mask2 <- matrix(1, nrow = length(gene_of_interest), ncol = ncol(fit), 
               dimnames = list(gene_of_interest, colnames(fit)))
for(id in gene_of_interest){
  mask[id, filter(nei, name == id)$neighborhood[[1]]] <- 1
  mask2[id, filter(nei, name == id)$neighborhood[[1]]] <- NA
}

# calculate mean inside and outside in neighborhood 
psce2 <- glmGamPoi::pseudobulk(SingleCellExperiment(list(inside = as.matrix(logcounts(fit)[gene_of_interest,,drop=FALSE] * mask),
                                                        outside = as.matrix(logcounts(fit)[gene_of_interest,,drop=FALSE] * mask2))),
                      group_by = vars(sample_id, dist.cluster), n = n(),
                      aggregation_functions = list(.default = \(...) matrixStats::rowMeans2(..., na.rm = TRUE)),
                      col_data = as.data.frame(colData(fit)))

comparison_data <- as_tibble(colData(psce2)) %>%
  mutate(expr_inside = as_tibble(t(assay(psce2, "inside"))),
         expr_outside = as_tibble(t(assay(psce2, "outside")))) %>%
  unpack(starts_with("expr"), names_sep = "-") %>%
  pivot_longer(starts_with("expr"), names_sep = "[-_]", names_to = c(".value", "origin", "symbol")) 

psce2
comparison_data
```

```{r}
comparison_data <- tibble(comparison_data) %>%
  mutate(dist.cluster = ordered(dist.cluster, levels = levels(fit$colData$dist.cluster))) %>%
  arrange(dist.cluster)

expr_comparison_original_mean_pl <- comparison_data %>%
  ggplot(aes(x = dist.cluster, y = expr)) +
    geom_point(aes(color = origin), size = 1, alpha = 0.5) +
    geom_smooth(aes(color = origin, x = as.integer(dist.cluster)), method = 'gam', formula = y ~ s(x, bs = "cs", k = 3), se = FALSE, linewidth = 2) +

    scale_color_manual(values = c("inside" = "black", "outside" = "lightgrey"), labels = c("inside" = "pixels in neighborhood", "outside" = "All other pixels")) +
    # scale_y_continuous(limits = c(0, 3), expand = expansion(add = 0)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression(log transformed)",
         subtitle = paste0(gene_of_interest, " expr. vs. Dist to endothelial cell annot. by ", marker.sel))  +
    theme(plot.subtitle = element_text(size = 7))

expr_comparison_original_mean_pl
```

### Bootstrap for mean

```{r}
mask <- matrix(NA, nrow = length(gene_of_interest), ncol = ncol(fit), 
               dimnames = list(gene_of_interest, colnames(fit)))

mask2 <- matrix(1, nrow = length(gene_of_interest), ncol = ncol(fit), 
               dimnames = list(gene_of_interest, colnames(fit)))

for(id in gene_of_interest){
  mask[id, filter(nei, name == id)$neighborhood[[1]]] <- 1
  mask2[id, filter(nei, name == id)$neighborhood[[1]]] <- NA
}


sce.pseudo <- SingleCellExperiment(
  list(inside = as.matrix(logcounts(fit)[gene_of_interest,,drop=FALSE] * mask),
  outside = as.matrix(logcounts(fit)[gene_of_interest,,drop=FALSE] * mask2)
  ),
  colData = as.data.frame(colData(fit))
  )

mean_stat <- function(data, indices) {
  return(mean(data$counts[indices, ], na.rm = TRUE))
}

# Function to perform bootstrapping and add orig and expr columns
perform_bootstrapping <- function(origin, expr_label) {
  tibble(counts = as.data.frame(assay(sce.pseudo, origin)[1,])) %>% 
    mutate(dist.cluster = sce.pseudo$dist.cluster) %>% 
    filter(complete.cases(counts)) %>% 
    group_by(dist.cluster) %>% 
    do({
      boot.res <- boot(., statistic = mean_stat, R = 1000)
      ci <- boot.ci(boot.res, conf = c(0.95), type = c('perc'))
      data.frame(expr = boot.res$t, n = nrow(.), lower = ci$percent[4], upper = ci$percent[5])
    }) %>% 
    ungroup() %>%
    mutate(origin = origin, symbol = expr_label)
}

# Perform bootstrapping for both "inside" and "outside"
comparison_data <- bind_rows(
  perform_bootstrapping("inside", gene_of_interest),
  perform_bootstrapping("outside", gene_of_interest)
)
max(comparison_data$expr)
```

```{r}
comparison_data <- tibble(comparison_data) %>%
  mutate(dist.cluster = ordered(dist.cluster, levels = levels(fit$colData$dist.cluster))) %>%
  arrange(dist.cluster)

expr_comparison_pl <- comparison_data %>%
  ggplot(aes(x = dist.cluster, y = expr)) +
    geom_point(aes(color = origin), size = 1, alpha = 0) +
    geom_smooth(aes(color = origin, x = as.integer(dist.cluster)), method = 'gam', formula = y ~ s(x, bs = "cs", k = 5), se = FALSE, linewidth = 1) +
    geom_errorbar(aes(ymin = lower, ymax = upper, color = origin), width = 0.8, alpha = 0.5) +

    scale_color_manual(values = c("inside" = "black", "outside" = "lightgrey"), labels = c("inside" = "pixels in neighborhood", "outside" = "All other pixels")) +
    # scale_y_continuous(limits = c(0, 2), expand = expansion(add = 0)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression(log transformed)",
         subtitle = paste0(gene_of_interest, " expr. vs. Dist to endothelial cell annot. by ", marker.sel, " - 0.95 confidence interval"))  +
    theme(plot.subtitle = element_text(size = 7))

expr_comparison_pl
```

```{r}
filename <- paste0("correlation plot of dists - bootstrap mean",  ".png")
ggsave(filename = file.path(res.dir, "plots", filename), plot = expr_comparison_pl, device = "png", width = 10, height = 8, dpi = 700)
```

```{r}
expr_comparison_violin <- comparison_data %>%
  mutate(dist.cluster = ordered(dist.cluster, levels = levels(fit$colData$dist.cluster))) %>% 
  ggplot(aes(x = dist.cluster, y = expr, fill = origin)) +
    geom_violin(trim = F) +
    # geom_smooth(aes(color = origin, x = as.integer(dist.cluster)), span = 1.5, spe = FALSE, linewidth = 2) +
    scale_fill_manual(values = c("inside" = "black", "outside" = "lightgrey"), labels = c("inside" = "pixels in neighborhood", "outside" = "All other pixels")) +
    # scale_y_continuous(limits = c(0, 2), expand = expansion(add = 0)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression",
         subtitle = paste0(gene_of_interest, " expr. vs. Dist to endothelial cell - bootstrapped mean"))  +
    theme(plot.subtitle = element_text(size = 7))

expr_comparison_violin

filename <- paste0("expr_comparison_violin",  ".png")
ggsave(filename = file.path(res.dir, "plots", filename), plot = expr_comparison_violin, device = "png", width = 10, height = 8, dpi = 700)
```

```{r}
expr_comparison_scatter <- comparison_data %>%
  mutate(dist.cluster = ordered(dist.cluster, levels = levels(fit$colData$dist.cluster))) %>% 
  ggplot(aes(x = dist.cluster, y = expr)) +
    geom_point(aes(color = origin), size = 1) +
    # geom_smooth(aes(color = origin, x = as.integer(dist.cluster)), span = 1.5, spe = FALSE, linewidth = 2) +
    scale_color_manual(values = c("inside" = "black", "outside" = "lightgrey"), labels = c("inside" = "pixels in neighborhood", "outside" = "All other pixels")) +
    scale_y_continuous(limits = c(0, 2), expand = expansion(add = 0)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression",
         subtitle = paste0(gene_of_interest, " expr. vs. Dist to endothelial cell"))  +
    theme(plot.subtitle = element_text(size = 7))

expr_comparison_scatter
```

```{r}
filename <- paste0("correlation plot of dists_scatter",  ".png")
ggsave(filename = file.path(res.dir, "plots", filename), plot = expr_comparison_scatter, device = "png", width = 10, height = 8, dpi = 500)
```

```{r, paged.print=FALSE}
is_inside <- tibble(symbol = gene_of_interest, cell_id = list(colnames(fit))) %>%
  left_join(dplyr::select(nei, name, neighborhood), by = c("symbol"= "name")) %>%
  mutate(inside = map2(cell_id, neighborhood, \(ref, nei_pixels) ref %in% nei_pixels)) %>%
  dplyr::select(-neighborhood) %>%
  unnest(c(inside, cell_id))

```

```{r}
qs::qsave(is_inside, file.path(res.dir, "is_inside.qs"))

```

## UMAP DE

```{r}
de_plot_data <- as_tibble(colData(fit), rownames = "cell_id") %>%
  mutate(umap = umap) %>%
  mutate(de = as_tibble(t(assay(fit[gene_of_interest,], "DE")))) %>%
  unnest(de, names_sep = "-") %>%
  pivot_longer(starts_with("de-"), names_sep = "-", values_to = "de", names_to = c(NA, "symbol")) %>%
  inner_join(is_inside, by = c("symbol", "cell_id")) %>%
  sample_frac(size = 1) 

abs_max <- max(abs(quantile(de_plot_data$de, c(0.95, 0.05))))

dist_de_pl <- de_plot_data %>%
  mutate(inside = ifelse(inside, "in", "out")) %>%
  mutate(inside = factor(inside, levels = c("in", "out")))  %>%
  ggplot(aes(x = umap[,2], y = umap[,1])) +
    ggrastr::rasterise(geom_point(aes(color = de), size = 0.5, stroke = 0), dpi = 600) +
    # scale_colour_gradient2_rev(limits = c(-1, 1) * abs_max, oob = scales::squish, breaks = c(-1, 0, 1) * signif_to_zero(abs_max, 1), mid = "lightgrey") +
    scale_color_de_gradient(abs_max, mid_width = 0.2) +
    facet_grid(vars(inside), labeller = labeller(inside = as_labeller(c("in" = "pixels in Neighb.", "out" = "All other pixels"))),
               switch="y") +
    small_axis("", fontsize = font_size_small) +
    theme(legend.position = "bottom", legend.margin = margin(t = -2, unit = "mm")) +
    guides(color = guide_colorbar(barheight = unit(1, "mm"), barwidth = unit(15, "mm"), title.vjust = 1)) +
    labs(color = "$\\Delta$")

dist_de_pl
```

```{r}
filename <- paste0("UMAP_DE",  ".png")
ggsave(filename = file.path(res.dir, "plots", filename), plot = dist_de_pl, device = "png", width = 10, height = 14, dpi = 800)
```

```{r, paged.print=FALSE}
# calculate the frac inside origin group!!
rel_plt <- colData(fit) %>%
  as_tibble(rownames = "cell_id") %>%
  left_join(is_inside) %>%
  dplyr::count(dist.cluster, symbol, inside) %>%
  mutate(frac = n / sum(n), .by = c(symbol, inside)) %>%  # calculate the frac inside origin group!!
  mutate(dist.cluster = fct_relabel(dist.cluster, \(x) str_replace(x, ",", ", "))) %>%
  ggplot(aes(x = dist.cluster, y = frac)) +
    geom_col(aes(fill = inside), position = position_dodge2()) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    scale_x_discrete(position = "top") +
    scale_fill_manual(values = c("TRUE" = "black", "FALSE" = "lightgrey")) +
    guides(x = guide_axis(angle = 90)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Rel. No. pixels - Group-Wise Fractions")

rel_plt 

# calculate the frac overall: divide by total amount of spots
rel_plt_2 <- colData(fit) %>%
  as_tibble(rownames = "cell_id") %>%
  left_join(is_inside) %>%
  dplyr::count(dist.cluster, symbol, inside) %>%
  mutate(total_n = sum(n), .by = symbol) %>%  # Calculate total count per symbol
  mutate(frac = n / total_n, .by = c(symbol, inside)) %>%  # calculate the frac inside origin group!!
  mutate(dist.cluster = fct_relabel(dist.cluster, \(x) str_replace(x, ",", ", "))) %>%
  ggplot(aes(x = dist.cluster, y = frac)) +
    geom_col(aes(fill = inside), position = position_dodge2()) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    scale_x_discrete(position = "top") +
    scale_fill_manual(values = c("TRUE" = "black", "FALSE" = "lightgrey")) +
    guides(x = guide_axis(angle = 90)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Rel. No. pixels - Overall Fractions")

rel_plt_2
```

## Save plot

```{r}
plot <- expr_comparison_pl /rel_plt_2
filename <- paste0("prop plot of dists_scatter",  ".png")
ggsave(filename = file.path(res.dir, "plots", filename), plot = plot, device = "png", width = 10, height = 14, dpi = 800)

plot
```

```{r}
plot <- expr_comparison_original_mean_pl /rel_plt_2
filename <- paste0("expr_comparison_original_mean_pl",  ".png")
ggsave(filename = file.path(res.dir, "plots", filename), plot = plot, device = "png", width = 10, height = 14, dpi = 800)

plot
```

## Gene counts

```{r}
nei.bc <- rownames(pos[is_inside$inside, ])
as_tibble(pos) %>%
  mutate(bc = rownames(pos)) %>%
  ggplot(aes(x = x, y = y)) +
    geom_point(size = 1, color = "grey") +
    gghighlight(bc %in% nei.bc) +
    geom_point(col = "black", size = 1) +
    labs(title = paste0("Neiberhood spots"), x = "pxl_row_in_fullres", y = "pxl_col_in_fullres")

```

## Misc.
