---
title: "Deconvolution"
output:
  html_document:
    df_print: paged
output.width: "75%"
---

# Library

```{r}
library(Matrix)
library(ggplot2)
library(gghighlight)
library(tidyverse)
library(dplyr)


library(STdeconvolve)
library(SpatialExperiment)
library(lemur)
library(igraph)
library(qs)

library(spacexr)
library(purrr)

library(ggcorrplot)

```

```{r}
source("../src/util.R")
```

# Load data

```{r}
set.seed(5)
```

```{r}
# path for S3IT
data_dir <- '/shares/rheumatologie.usz/caroline/spatial'

# path for local
data_dir <- '../data'
biopsy_dirs <- get.dirs(data_dir)
```

```{r}
dir <-  biopsy_dirs[["SHK166_RA_Knee"]]
se <- load.data(dir)
```

# Deconvolution

## STDeconvolve

```{r}
prior.k <- 19
# select the LDA model of interest and get the beta (cell-type transcriptional profiles) and theta (cell-type barcode proportions) matrices.
res.path <- "../results/deconvolution/STDeconvolve/ldas.qs"
if (!file.exists(res.path)) {
  source("../scripts/deconvolution/STDeconvolve.R")
}
ldas <- qs::qread(res.path)

# ldas$kneedOptK
optLDA <- optimalModel(models = ldas, opt = prior.k)
results <- getBetaTheta(optLDA, perc.filt = 0.05, betaScale = 1000)
deconProp <- results$theta
deconGexp <- results$beta
```

```{r}
opt.K <- 19
## visualize deconvolved cell-type proportions
vizAllTopics(deconProp, pos[rownames(deconProp),], r=55, lwd=0)	  

## interpret these cell-types based on their gene expression
topGenes(deconGexp)
## top genes based on log 2 (fold change) for each cell-type
lapply(1:opt.K, function(i) {
  head(sort(log2(deconGexp[i,]/colMeans(deconGexp[-i,])), decreasing=TRUE))
})
```

```{r}
lapply(1:opt.K, function(i) {
vizTopic(theta = deconProp, pos = pos, topic = i, plotTitle = i,
         size = 1, stroke = 0, alpha = 0.5,
         low = "white",
         high = "red")
})
```

### Annotation strategy

```{r}
# load reference data set
dir.cluster <- "~/data/"
dir.local <- "../../Spatial/"
ref.name <- "ref_from_merged_subpop_down_main_clusters_for_CCI.rds"

ref.dir <- dir.cluster
if (!dir.exists(ref.dir)) {
  ref.dir <- dir.local
}

ref <- readRDS(paste0(ref.dir, ref.name))

ctypes <- ref@cell_types
levels(ctypes)
which(unique(ctypes) == "Endothelial Cells" )

ref.counts <- t(ref@counts) # ctype x gene
dim(ref.counts)

genes.sel <- colnames(deconGexp)
ref.counts <- ref.counts[,genes.sel]

# gene profiles
dim(ref.counts)
mean.na.rm <- partial(mean, na.rm = TRUE)
rownames(ref.counts) <- ctypes
ref.counts <- as.matrix(ref.counts) %>%
            as.data.frame() %>%
            mutate(ctypes = ctypes)
  
ref.gexp <- aggregate(.~ ctypes, data = ref.counts, FUN = mean.na.rm) %>% as.matrix()

ref.gexp <- ref.gexp[, -1]
mode(ref.gexp) <- "numeric"
```

```{r}
dim(deconGexp)
dim(gexp)
corMtx_beta <- getCorrMtx(# the deconvolved cell-type `beta` (celltypes x genes)
                          m1 = as.matrix(deconGexp),
                          # the reference `beta` (celltypes x genes)
                          m2 = as.matrix(ref.gexp),
                          # "b" = comparing beta matrices, "t" for thetas
                          type = "b")
```

```{r}
## row and column names need to be characters
rownames(corMtx_beta) <- paste0("decon_", seq(nrow(corMtx_beta)))

correlationPlot(mat = corMtx_beta,
                colLabs = "Deconvolved cell-types",
                rowLabs = "Ground truth cell-types",
                title = "Transcriptional correlation",   annotation = T) +
  ## this function returns a `ggplot2` object, so can add additional aesthetics
ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 0, size = 6),
                  axis.text.y = ggplot2::element_text(size = 8))

library(ggcorrplot)

# Create the correlation plot
ggcorrplot(
  corMtx_beta,
  hc.order = TRUE,
  lab_size = 2, 
  lab = T,
  insig = "blank",
  title = "Transcriptional correlation"
) + 
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 0, size = 6),
                  axis.text.y = ggplot2::element_text(size = 8)) 


order(corMtx_beta[16,], decreasing = T)
corMtx_beta[16, 1]
```

```         
```

## RCTD

```{r}
res.rctd <- readRDS(paste0(ref.dir, "SHK166_RCTD.rds"))
cell_type_info <- res.rctd@cell_type_info
res.rctd <- res.rctd@results
dim(res.rctd[[1]])
# cell_type_info$renorm
deconProp.rctd <- res.rctd$weights %>% as.matrix()

```

```{r}
# pos
# deconProp
# class(deconProp.rctd)
# deconProp.rctd
colnames(deconProp.rctd) <- seq_len(ncol(deconProp.rctd))
rownames(deconProp.rctd) <- rownames(pos)
i <- 16
vizTopic(theta = deconProp.rctd, pos = pos, topic = i, plotTitle = i,
         size = 1, stroke = 0, alpha = 0.5,
         low = "white",
         high = "red")
```

# Define covariate

## Proximity to a specific cell type

```{r}
pos <- spatialCoords(se)
pos <- pos[, c('x','y')]
pos <- as.matrix(pos)
pos
plot(pos)

# find interval between adjacent points 
pos.sorted <- pos[order(pos[,1], decreasing = FALSE),]
pos.diff <- pos.sorted[2:nrow(pos.sorted), ] - pos.sorted[1:nrow(pos.sorted) -1 , ]
hist(pos.sorted[,2], breaks = 100)
hist(pos.diff[,1], breaks = c(0, 1, 3, 5, max(pos.diff[,1])))

pos.sorted <- pos[order(pos[,2], decreasing = FALSE),]
pos.diff <- pos.sorted[2:nrow(pos.sorted), ] - pos.sorted[1:nrow(pos.sorted) -1 , ]
hist(pos.diff[,2], breaks = c(0, 1, 3, 5, max(pos.diff[,2])))
```

```{r}
# Define target cell types
topic.target <- "9"
prop.threshold <- 0.5  
weight <- NULL

# dim(deconProp)
# dim(deconGexp)
# heatmap(deconGexp)

deconProp_target <- deconProp[,topic.target]
deconProp_target <- deconProp_target[deconProp_target > prop.threshold]

length(deconProp_target)
bc.target <- names(deconProp_target)
pos.target <-  pos[bc.target,]
```

```{r}
head(pos)
class(pos[1,][[1]])
adjacency.matrix <- get.adjacency.matrix(pos, nei.diff = seq(0,5))
sum(adjacency.matrix)
```

```{r}
# build a graph
g <- graph_from_adjacency_matrix(adjacency.matrix, mode = 'undirected')
length(components(g)$membership)

bc.idxs <- seq.int(nrow(pos))

target.idxs <- which(rownames(pos) %in% rownames(pos.target))
min.dists.mat <- get.min.dists.mat(g, bc.idxs, target.idxs)
```

```{r}
length(deconProp_target)
dim(min.dists.mat)
min.dists.mat
# Calculate min dist: use graph later, not connected
min.dists.mat.finite <- min.dists.mat[is.finite(min.dists.mat)]
spl.norm <- (min.dists.mat - min(min.dists.mat)) / (max(min.dists.mat.finite) - min(min.dists.mat))
spl.norm.prop <- sweep(spl.norm, 2, deconProp_target, FUN="/") # divide each row by target vector
dists.min <- rowMins(spl.norm.prop)
names(dists.min) <- rownames(pos)

se$dists.min <- min.dists.mat
se
dists.min
```

```{r}
# some spots are filled out by quality control
pos <- pos[rownames(deconProp),]

as_tibble(pos) %>%
  mutate(bc = rownames(pos)) %>%
  ggplot(aes(x = x, y = y)) +
    geom_point(size = 1, color = "grey") +
    gghighlight(bc %in% rownames(pos.target)) +
    geom_point(col = "blue", size = 1) +
    labs(title = paste0("Topic - ", topic.target), x = "pxl_row_in_fullres", y = "pxl_col_in_fullres")

as_tibble(pos) %>%
  mutate(prop = deconProp[, topic.target]) %>%
  ggplot(aes(x = x, y = y)) +
    geom_point(aes(color = prop), size = 1, stroke = 0) +
    scale_color_gradient2()
```

# LEMUR

```{r}
cont2ordered <- function(x, n, from = min(x), to = max(x), add_label = TRUE, label_fmt = "%.2f"){
  groups <- seq(from, to, length.out = n+1)
  res <- rep(NA_integer_, length(x))
  labels <- rep(NA_character_, n)
  for(idx in seq_len(n)){
    if(idx == n){
      labels[idx] <- paste0("[", sprintf(label_fmt, groups[idx]), ",", sprintf(label_fmt, groups[idx+1]), "]")
      res[x >= groups[idx] & x <= groups[idx+1]] <- idx
    }else{
      labels[idx] <- paste0("[", sprintf(label_fmt, groups[idx]), ",", sprintf(label_fmt, groups[idx+1]), ")")
      res[x >= groups[idx] & x < groups[idx+1]] <- idx
    }
  }
  if(add_label){
    ordered(res, levels = seq_len(n), labels = labels)
  }else{
    res
  }
}

cont2ordered(seq(0, 30), n = 6, label_fmt = "%.f")
levels(cont2ordered(sce_subset$dist, n = 10, label_fmt = "%.2f"))
```

```{r}
sce_subset$dist_cluster <- cont2ordered(sce_subset$dist, n = 10, label_fmt = "%.2f")
```

```{r}
{r}
as_tibble(colData(sce_subset)) %>%
  mutate(umap = umap) %>%
  ggplot(aes(x = umap[,1], y = umap[,2])) +
    geom_point(aes(color = sample), size = 0.3, stroke = 0) +
    guides(color = guide_legend(override.aes = list(size = 1)))

as_tibble(colData(sce_subset)) %>%
  mutate(umap = umap) %>%
  ggplot(aes(x = umap[,1], y = umap[,2])) +
    geom_point(aes(color = cell_type_lumped), size = 0.3, stroke = 0) +
    guides(color = guide_legend(override.aes = list(size = 1)))

as_tibble(colData(sce_subset)) %>%
  mutate(umap = umap) %>%
  ggplot(aes(x = umap[,1], y = umap[,2])) +
    geom_point(aes(color = dist), size = 0.3, stroke = 0) +
    scale_color_viridis_b()
```

```{r}
set.seed(1)
fit <- lemur::lemur(sce_subset, design = ~ dist_cluster, n_embedding = 30, test_fraction = 0.6)
set.seed(1)
fit <- lemur::align_harmony(fit)
```

```{r}
{r}
fit <- lemur::test_de(fit, cond(dist_cluster = "[0.90,1.00]") - cond(dist_cluster = "[0.00,0.10)"))
set.seed(1)
nei <- lemur::find_de_neighborhoods(fit, group_by = vars(dist_cluster, sample), test_method = "edgeR")
```

```{r}
qs::qsave(sce_subset, "../data/cable_spatial_plaque_data/annotated_sce.qs")
```

```{r}
fit_small <- fit["Jun",]
nei_small <- nei %>% filter(name == "Jun")

qs::qsave(fit_small, "../output/cable_spatial_plaque_data/fit_small.qs")
qs::qsave(nei_small, "../output/cable_spatial_plaque_data/nei_small.qs")
```

# Misc

```{r}
library(purrr)

# Create a partial function for mean with na.rm = TRUE
mean_na_rm <- partial(mean, na.rm = TRUE)

# Sample data frame
data <- data.frame(
  group = c('A', 'A', 'B', 'B'),
  value1 = c(1, 2, NA, 4),
  value2 = c(5, NA, 7, 8)
)

# Using aggregate with the partial function
result <- aggregate(. ~ group, data = data, FUN = mean_na_rm)

print(result)

```

```{r}
library(igraph)

# Create a sample graph (you can replace this with your own graph)
g <- graph.ring(10)
g <- add_vertices(g, 3, color = "red")
plot(g)

# Check if vertices 1 and 2 are connected
are.connected(g, 1, 12)  # TRUE

cl <- components(g)
class(cl)

```

```{r}
# Create a simple unweighted graph
# Example edge list
edges <- data.frame(from = c(0, 1, 1, 2), to = c(1, 2, 3, 3))

# Create a graph from the edge list
graph <- graph.data.frame(edges, directed = FALSE)  # Adjust 'directed' as needed


# Specify source and target vertices
source <- 1
target <- 3

# Find the shortest path
shortest_paths <- shortest_paths(graph, from = source, to = target)
shortest_paths$vpath
# Check if a path exists
if (length(shortest_paths) > 0) {
    # Access the first shortest path (modify as needed)
    shortest_path <- shortest_paths[[1]]

    cat("Shortest path:", shortest_path)
} else {
    cat("No path exists between", source, "and", target)
}


```

```{r}
path <- "/shares/rheumatologie.usz/caroline/spatial/SHK166_RA_Knee/deconvolution/deconvolution_k10/deconvolution_topic_features_k10.csv"
deconvolution_topic_features_k10 <- read.csv(path)
head(deconvolution_topic_features_k10)
colnames(deconvolution_topic_features_k10)

path <- "/shares/rheumatologie.usz/caroline/spatial/SHK166_RA_Knee/deconvolution/deconvolution_k10/deconvolved_spots_k10.csv"
deconvolved_spots_k10 <- read.csv(path)
head(deconvolved_spots_k10)
```

```{r}
# Create a matrix (you can replace this with your own data)
my_matrix <- matrix(c(1, 2, 3, 4, 5, 6, 3, 3, -Inf), ncol = 3)

# Calculate row minimums, ignoring NA values
row_mins <- rowMins(my_matrix, na.rm = TRUE)

# Print the result
print(row_mins)

```

# Reference

-   Tutorial from Prof. Jean Fan, <https://jef.works/blog/2023/05/29/stdeconvolve-breast-cancer/>

-   STdeconvolve Vignettes, <https://www.bioconductor.org/packages/release/bioc/vignettes/STdeconvolve/inst/doc/vignette.html#spatialexperiment-inputs>
