------------------------------------------------------------------------

---
title: "QC"
output:
  html_document:
    df_print: paged
output.width: "75%"
---

# Library

```{r}
library(Matrix)
library(ggplot2)
library(tidyverse)
library(stringr)

library(SpatialExperiment)
library(lemur)
library(igraph)
library(qs)

# library(dplyr)
library(Seurat)
library(png)
library(glue)
library(grid)
library(EBImage)
library(jsonlite)
library(magick)

```

# Data

```{r}
dir <- get.data.dir()
res.dir <- get.res.dir()

dir.data.processed <- file.path(dir, "processed")
spe <- qread(file.path(dir.data.processed, "spe_clean.qs"))

# load reference data set
ref <- qread(file.path(res.dir, "SCE/sce.qs"))

```

# Violin

```{r}
col_sums_spatial <- tibble(type = "spatial", bc = colnames(spe), colSum = colSums(counts(spe)))

# subset genes
ref.subset <- ref[rownames(spe),]
ref.subset
col_sums_sce <- tibble(type = "sce", bc = colnames(ref.subset), colSum = colSums(counts(ref.subset)))
hist(col_sums_sce$colSum)
col_sums <- rbind(col_sums_spatial, col_sums_sce)

# Create a violin plot
  ggplot() +
    geom_violin(data = col_sums, aes(x = type, y =colSum), trim = FALSE, fill = "lightblue") +
    stat_summary(fun.data = "median_hilow", 
                 geom = "errorbar", 
                 fun.args = list(conf.int = 0.95), 
                 width = 0.2, 
                 linetype = "dashed", # Dashed lines
                 color = "black") + 
    theme_minimal() +
    labs(title = "Violin Plot of counts",
         x = "Dataset types", 
         y = "ColSums")

```
