---
title: "scRNA-seq"
output:
  html_document:
    df_print: paged
output.width: "75%"
---

# Library

```{r}
library(Matrix)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(patchwork)

library(STdeconvolve)
library(SpatialExperiment)
library(SingleCellExperiment)

library(lemur)
library(qs)

library(purrr)

library(stringr)
library(Seurat)
library(harmony)
library(cowplot)
```

```{r}
source("../../src/util.R")
source("../../config/config.R")
```

# Prepare Data

## Load data

```{r}
set.seed(5)
```

```{r}
# load reference scRNA-seq
# fine.ref <- readRDS("/data/myi/mt-spatial-transcriptomics/data/scRNA-seq/merged_subpop_down_for_CCI.RDS")
# 
# counts.sc <- fine.ref@assays$RNA@data
# ctypes <- fine.ref@active.ident
# prefix.bcs <- colnames(counts.sc)
# dim(counts.sc)

# load reference scRNA-seq: the first one 10,000
ref_path <- get.refd.path()
ref_path
ref <- readRDS(ref_path)
counts.sc <- ref@counts
ctypes <- ref@cell_types
prefix.bcs <- colnames(counts.sc)

sum(which(colnames(counts.sc) != names(ctypes)))
```

```{r}
# locate prefix without digits
prefixs <- lapply(prefix.bcs, function(i) {
                      outs <- str_locate_all(i, "_")[[1]]
                      last <- outs[nrow(outs), 1, drop = T]
                      digit.idx <- str_locate(i, "\\d")
                      if (!is.na(digit.idx[1,1])) {
                        last <- digit.idx[1,1]
                      }
                      sub <- substring(i, 1, last - 1)
                      return(sub)}
)

prefixs2 <- lapply(prefix.bcs, function(i) {
                      outs <- str_locate_all(i, "_")[[1]]
                      last <- outs[1, 1, drop = T]
                      sub <- substring(i, 1, last - 1)
                      return(sub)}
)


sce <- SingleCellExperiment(
  assays = list(counts =counts.sc)
)
sce

prefixs <- unlist(prefixs, recursive = T)
sce$samples <- prefixs

prefixs2 <- unlist(prefixs2, recursive = T)
sce$cell.group.4 <- prefixs2

sce$ctypes <- ctypes
logcounts(sce) <- transformGamPoi::shifted_log_transform(sce)

```

## UMAP

```{r}
umap <- scater::calculateUMAP(logcounts(sce), scale = T)
reducedDim(sce, "UMAP_scater", withDimnames = FALSE) <- umap

sce
```

## clustering

### Seurat: KNN and Louvain

```{r}
otherCells <- as_tibble(colData(sce)) %>% 
                group_by(cell.group.4) %>% 
                distinct(ctypes) %>% 
                filter(cell.group.4 == "otherCells")

cell.group.7 <- sce$cell.group.4
idxs <- which(cell.group.7 == "otherCells")
cell.group.7[idxs] <- as.character(sce$ctypes[idxs]) # factor to character

# fix typo
cell.group.7[which(cell.group.7 == "Meyloid")] <-  "Myeloid"
cell.group.7 <-  factor(cell.group.7)

sce$cell.group.7 <- cell.group.7

table(sce$cell.group.7)
```

```{r}
# Convert to Seurat object
seurat_obj <- as.Seurat(sce, counts = "counts")

seurat_obj@active.ident <- seurat_obj$cell.group.7
seurat_obj <- seurat_obj %>% 
              NormalizeData(verbose = FALSE) %>%
              FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>%
              ScaleData(verbose = FALSE) %>%
              RunPCA(features = VariableFeatures(.), npcs = 50, verbose = FALSE) %>%
              RunUMAP(dims = 1:10)

seurat_obj <- FindNeighbors(seurat_obj, dim = 1:10)
seurat_obj <- FindClusters(seurat_obj, resolution = 0.1)
table(seurat_obj$seurat_clusters)
ElbowPlot(seurat_obj)
DimPlot(seurat_obj)

umap_seurat <- seurat_obj@reductions$umap@cell.embeddings
sce$seurat_clusters <- seurat_obj$seurat_clusters

```

```{r}
unique.cg <- unique(sce$cell.group.7)
hl.type <- unique.cg[1]
plot.cg <- function(hl.type) {
   
    color.group <- rep("grey", 7)
    names(color.group) <- unique.cg
    color.group[[hl.type]] <- "blue"
    
    plot <- as_tibble(colData(sce)) %>%
      mutate(umap = umap_seurat) %>%
      ggplot(aes(x = umap[,1], y = umap[,2])) +
        geom_point(aes(color = cell.group.7), size = 0.5) +
        scale_colour_manual(values = color.group) +
        labs(title = "UMAP of cell.group.7")
}

plots <- lapply(unique.cg, plot.cg)
plots.grid <- cowplot::plot_grid(plotlist = plots, ncol = 3, rel_heights = 20)

ggsave(filename = "UMAP of cell.group.7.svg", plot = plots.grid, width = 8, height = 6)
ggsave(filename = "UMAP of cell.group.7.pdf", plot = plots.grid, width = 8, height = 6)

plots.grid
```

```{r}
plot.cg <- function(hl.type, num.group = 7) {
    
    hl.type <-  as.character(hl.type)
    color.group <- rep("grey", num.group)
    names(color.group) <- unique.cg
    color.group[[hl.type]] <- "blue"
    
    plot <- as_tibble(colData(sce)) %>%
      mutate(umap = umap_seurat) %>%
      ggplot(aes(x = umap[,1], y = umap[,2])) +
        geom_point(aes(color = seurat_clusters), size = 0.5) +
        scale_colour_manual(values = color.group) +
        labs(title = "UMAP of seurat cluster")
}

unique.cg <- unique(sce$seurat_clusters)
plots <- lapply(unique.cg, plot.cg)
plots.grid <- cowplot::plot_grid(plotlist = plots, ncol = 3, rel_heights = 20)

ggsave(filename = "UMAP of seurat cluster.svg", plot = plots.grid, width = 8, height = 6)
ggsave(filename = "UMAP of seurat cluster.pdf", plot = plots.grid, width = 8, height = 6)

plots.grid
```

```{r}
# filter for ECs
indicators <- !((sce$seurat_clusters == 0 | sce$seurat_clusters == 1) & sce$cell.group.7 == "Endothelial Cells")
sce.subset <- sce[ ,indicators]
sce.subset
        
```

### KMeans

```{r}
num.cluster <- 4
res.km <- kmeans(reducedDim(sce, "umap", withDimnames = FALSE), centers = num.cluster)
clusters <- as.factor(res.km$cluster)
sce$kmeans_clusters <- clusters
```

## Save SCE data

```{r}
# file <- file.path(proj.dir.cluster, "data/counts_sc.csv")
# write.csv(counts.sc, file = file, row.names = TRUE)

dir.res <- get.res.dir()
qsave(sce, file.path(dir.res, "SCE", "sce.qs"))
```

# Visualization

```{r}
as_tibble(colData(sce)) %>%
  mutate(umap = umap) %>%
  ggplot(aes(x = umap[,1], y = umap[,2])) +
    geom_point(aes(color = ctypes), size = 0.5) +
    labs(title = "UMAP of logcounts")

```

```{r}
unique.cg <- unique(sce$cell.group.4)
hl.type <- unique.cg[1]
plot.cg <- function(hl.type) {
   
    color.group <- rep("grey", 4)
    names(color.group) <- unique.cg
    color.group[[hl.type]] <- "blue"
    
    plot <- as_tibble(colData(sce)) %>%
      mutate(umap = umap) %>%
      ggplot(aes(x = umap[,1], y = umap[,2])) +
        geom_point(aes(color = cell.group.4), size = 0.5) +
        scale_colour_manual(values = color.group) +
        labs(title = "UMAP of cell.group.4")
}

plots <- lapply(unique.cg, plot.cg)
plots.grid <- cowplot::plot_grid(plotlist = plots, ncol = 2, rel_heights = 20)

ggsave(filename = "UMAP of cell.group.4.pdf", plot = plots.grid, device = "pdf", width = 8, height = 6)

plots.grid
```

```{r}
unique.cg <- unique(sce$cell.group.7)
hl.type <- unique.cg[1]

plot.cg <- function(hl.type) {
   
    color.group <- rep("grey", 7)
    names(color.group) <- unique.cg
    color.group[[hl.type]] <- "blue"
    
    plot <- as_tibble(colData(sce)) %>%
      mutate(umap = umap) %>%
      ggplot(aes(x = umap[,1], y = umap[,2])) +
        geom_point(aes(color = cell.group.7), size = 0.5) +
        scale_colour_manual(values = color.group) +
        labs(title = "UMAP of cell.group.7")
}

plots <- lapply(unique.cg, plot.cg)
plots.grid <- cowplot::plot_grid(plotlist = plots, ncol = 3, rel_heights = 20)

ggsave(filename = "UMAP of cell.group.7.svg", plot = plots.grid, width = 8, height = 6)
ggsave(filename = "UMAP of cell.group.7.pdf", plot = plots.grid, width = 8, height = 6)

plots.grid
```

```{r}
unique.cg <- as_tibble(colData(sce)) %>% 
             filter(cell.group.7 == "SynFib") %>% 
              select(ctypes) %>% 
              unique(ctypes) %>% 
              pull(ctypes)
unique.cg
# hl.type <- unique.cg[1]

plot.cg <- function(hl.type) {
    color.group <- rep("grey", 7)
    names(color.group) <- unique.cg
    color.group[[hl.type]] <- "blue"
    
    plot <- as_tibble(colData(sce)) %>%
      mutate(umap = umap) %>%
      filter(cell.group.7 == "SynFib") %>% 
      ggplot(aes(x = umap[,1], y = umap[,2])) +
        geom_point(aes(color = ctypes), size = 0.5) +
        scale_colour_manual(values = color.group) +
        labs(title = "UMAP of SynFib")
}

plots <- lapply(unique.cg, plot.cg)
plots.grid <- cowplot::plot_grid(plotlist = plots, ncol = 3, rel_heights = 20)

ggsave(filename = "UMAP of SynFib.svg", plot = plots.grid, width = 8, height = 6)
ggsave(filename = "UMAP of SynFib.pdf", plot = plots.grid, width = 8, height = 6)

plots.grid
```

# Misc.

```{r}
# fine.ref <- readRDS("/data/myi/mt-spatial-transcriptomics/data/scRNA-seq/merged_subpop_down_for_CCI.RDS")
# unique(fine.ref@active.ident)
# 
# main.ref <- readRDS("/data/myi/mt-spatial-transcriptomics/data/scRNA-seq/merged_subpop_down_main_clusters_for_CCI.RDS")
# unique(main.ref@active.ident)
# ncol(main.ref)
```

# Reference

-   Tutorial from Prof. Jean Fan, <https://jef.works/blog/2023/05/29/stdeconvolve-breast-cancer/>

-   STdeconvolve Vignettes, <https://www.bioconductor.org/packages/release/bioc/vignettes/STdeconvolve/inst/doc/vignette.html#spatialexperiment-inputs>

-   <https://portals.broadinstitute.org/harmony/articles/quickstart.html#integrating-cell-line-datasets-from-10x-1>
