---
title: "R Notebook"
---

# Library

```{r}
library(tidyverse)
library(SingleCellExperiment)
library(lemur)
library(SpatialExperiment)
library(patchwork)

library(boot)
library(Seurat)
library(tidyr) 
library(qs) 
library(glue) 
library(splines)


```

```{r}
source("../../src/util.R")
source("../../config/config.R")
```

# Load data

```{r}
res.dir <- get.res.dir()
res.dir.LEMUR <- file.path(get.res.dir(), "LEMUR")

# fit <- qs::qread(file.path(res.dir.LEMUR, "fit_small.qs"))
fit <- qs::qread(file.path(res.dir.LEMUR, "fit.qs"))

# nei <- qs::qread(file.path(res.dir.LEMUR, "nei_small.qs"))
nei_all <- qs::qread(file.path(res.dir.LEMUR, "nei.qs"))

spe <- qs::qread(file.path(res.dir.LEMUR, "se_dist.qs"))
spe
```

```{r}
# splineTimeR
diffExprs <- qread(file.path(res.dir, "diffExprs_spline.qs"))
target.genes <- c(diffExprs$genes[1:3], "THY1")

nei <- nei_all %>% filter(name %in% target.genes)
nei

marker.sel <- "VWF&PECAM1"
target.cell <- "ECs"

filename <- glue("ECs_manually_marker_final.qs")
is.ec.spot <- qread(file.path(res.dir, "deconvolution", filename))

# Kruskal-Wallis test
num_genes <- 500
pvals <- qread(file.path(res.dir, glue("pvals_kruskal_test_{num_genes}.qs")))


which.min(pvals)

which(pvals >= 0.05 & pvals <= 0.1)

which.max(pvals)

max(pvals, na.rm = T)
sum(pvals < 0.05, na.rm = T)
```

# Analysis

```{r}
marker.genes <- qread(file.path(res.dir, "markers.qs"))
markers.SynFib <- marker.genes %>% 
              filter(cluster == "SynFib") %>%
              filter(pct.1 > 0.25 & pct.2 >= 0 & avg_log2FC >= 0.5) %>%  # Marlia
              top_n(n = 200, wt = avg_log2FC) %>% 
              pull(gene)

"THY1" %in% markers.SynFib
```

```{r}
nei <- nei_all %>% filter(name %in% markers.SynFib)
idx <- nei$sel_statistic %>% which.min()
nei$name[idx]

gene_of_interest <- markers.SynFib %>% sample(1)
gene_of_interest <- markers.SynFib[1]
gene_of_interest <- "THY1"
gene_of_interest <- "PRG4"

P.Val <- NA
if (gene_of_interest %in% names(pvals) ) {
  P.Val <- pvals[[gene_of_interest]]
  P.Val <- round(P.Val, 3)
}

stat <- "mean"
```

## Dist plot of all pixels

```{r}
expr <-  counts(spe)[gene_of_interest,]
expr <- as.data.frame(expr)
expr <- as.numeric(unlist(expr))
table(expr)

expr_comparison_scatter <- as_tibble(colData(spe)) %>%
  mutate(dist.cluster = ordered(dist.cluster, levels = levels(spe$dist.cluster))) %>%
  mutate(expr = expr) %>%
  filter(!is.null(expr)) %>% 
  ggplot(aes(x = dist.cluster, y = expr, fill = dist.cluster)) +
    geom_violin(trim = FALSE) +
    # scale_y_continuous(limits = c(0, 10), expand = expansion(add = 0)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression",
         subtitle = paste0("All pixels - ", " expr. vs. Dist to endothelial cell"))  +
    theme(plot.subtitle = element_text(size = 7))

expr_comparison_scatter
```

```{r}
res.dir <- get.res.dir()
filename <- paste0("Violin plot of dists",  ".png")
ggsave(filename = file.path(res.dir, "plots", filename), plot = expr_comparison_scatter, device = "png", width = 10, height = 8, dpi = 500)
```

```{r}
expr <-  counts(spe)[gene_of_interest,]
expr <- as.data.frame(expr)
expr <- as.numeric(unlist(expr))
table(expr)

expr_comparison_scatter <- as_tibble(colData(spe)) %>%
  mutate(dist.cluster = ordered(dist.cluster, levels = levels(spe$dist.cluster))) %>%
  mutate(expr = expr) %>%
  filter(!is.null(expr)) %>% 
  ggplot(aes(x = dist.cluster, y = expr, fill = dist.cluster)) +
    geom_boxplot(alpha = 0.3) + # Add boxplots for reference
    stat_summary(
      fun = function(x) quantile(x, probs = 0.75), 
      geom = "point", 
      shape = 23, 
      size = 3, 
      fill = "red", 
      color = "black"
    ) + 
    scale_y_continuous(limits = c(0, 20), expand = expansion(add = 0)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression",
         subtitle = paste0("All pixels - ", " expr. vs. Dist to endothelial cell"))  +
    theme(plot.subtitle = element_text(size = 7))

expr_comparison_scatter
```

```{r}
expr <-  counts(spe)[gene_of_interest,]
expr <- as.data.frame(expr)
expr <- as.numeric(unlist(expr))
table(expr)

expr_comparison_scatter <- as_tibble(colData(spe)) %>%
  mutate(expr = expr) %>%
  ggplot(aes(x = min.dists, y = expr)) +
    geom_point(size = 1) +
    scale_y_continuous(limits = c(0, 20), expand = expansion(add = 0)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression",
         subtitle = paste0("All pixels - ", " expr. vs. Dist to endothelial cell"))  +
    theme(plot.subtitle = element_text(size = 7))

expr_comparison_scatter
```

## Dist Clusters in UMAP

```{r}
set.seed(1)
# umap <- uwot::umap(t(fit$embedding))
spe
umap <- reducedDim(spe, "umap_sel")
```

```{r}
as_tibble(colData(fit)) %>%
  mutate(umap = umap[colnames(fit),]) %>%
  ggplot(aes(x = umap[,1], y = umap[,2])) +
    geom_point(aes(color = dist.cluster), size = 0.7, stroke = 0) +
    guides(color = guide_legend(override.aes = list(size = 1)))
```

## DE matrix in UMAP

```{r}
DE <- assay(fit, "DE") 
DE_seurat <- CreateSeuratObject(counts = DE, data = DE) %>% 
  # NormalizeData(verbose = FALSE) %>%
  # FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>%
  ScaleData(verbose = FALSE) %>%
  RunPCA(features = rownames(.), verbose = FALSE) %>% 
  FindNeighbors(reduction = "pca", dims = 1:20) %>% 
  FindClusters(verbose = FALSE, resolution = 0.2) %>% 
  RunUMAP(reduction = "pca", dims = 1:20)
  
```

```{r}
p1 <- DimPlot(DE_seurat, reduction = "umap", label = TRUE, pt.size = 0.1)
p1
# p2 <- SpatialDimPlot(DE_seurat, label = TRUE, label.size = 3)
# p1.2 <- p1 + p2
```

## Correlation plot

### Bootstrap for mean/median

```{r}
set.seed(1)
mask <- matrix(NA, nrow = length(gene_of_interest), ncol = ncol(fit), 
               dimnames = list(gene_of_interest, colnames(fit)))

mask2 <- matrix(1, nrow = length(gene_of_interest), ncol = ncol(fit), 
               dimnames = list(gene_of_interest, colnames(fit)))

for(id in gene_of_interest){
  mask[id, filter(nei, name == id)$neighborhood[[1]]] <- 1
  mask2[id, filter(nei, name == id)$neighborhood[[1]]] <- NA
}


sce.pseudo <- SingleCellExperiment(
  list(inside = as.matrix(logcounts(fit)[gene_of_interest,,drop=FALSE] * mask),
  outside = as.matrix(logcounts(fit)[gene_of_interest,,drop=FALSE] * mask2)
  ),
  colData = as.data.frame(colData(fit))
  )

stat_func <- function(data, indices) {
  if (stat == "mean") {
    return(mean(data[indices], na.rm = TRUE))
  }
  return(median(data[indices], na.rm = TRUE))
}

# Function to perform bootstrapping and add orig and expr columns
perform_bootstrapping <- function(origin, expr_label) {
  tibble(counts = as.data.frame(assay(sce.pseudo, origin)[1,])) %>% 
    mutate(dist.cluster = sce.pseudo$dist.cluster) %>% 
    # filter(complete.cases(counts)) %>% 
    group_by(dist.cluster) %>% 
    do({
      data <- .$counts[!is.na(.$counts)]
      
      # in case no data to boot
      if (length(data) == 0) {
        expr <-  NA; lower <- NA; upper <- NA
      }else{
        boot.res <- boot(data, statistic = stat_func, R = 1000)
        ci <- boot.ci(boot.res, conf = c(0.95), type = c('perc'))
        expr <-  boot.res$t; lower <- ci$percent[4]; upper <- ci$percent[5]
      }
      
      data.frame(expr = expr, n = nrow(.), lower = lower, upper = upper)
    }) %>% 
    ungroup() %>%
    mutate(origin = origin, symbol = expr_label)
}


# Perform bootstrapping for both "inside" and "outside"
comparison_data <- bind_rows(
  perform_bootstrapping("inside", gene_of_interest),
  perform_bootstrapping("outside", gene_of_interest)
)
max(comparison_data$expr)
```

```{r}
comparison_data <- tibble(comparison_data) %>%
  mutate(dist.cluster = ordered(dist.cluster, levels = levels(fit$colData$dist.cluster))) %>%
  arrange(dist.cluster)

comparison_data$avg.dist <- lapply(as.character(comparison_data$dist.cluster), calculate.avg.dist) %>% unlist()

```

### correlation plot

```{r}
# set y limits
y_min <- min(comparison_data$expr)
y_max <- max(comparison_data$expr)
y_expansion <- 0.6

# degree of freedom of natural cubic spline 
df <- 3

expr_comparison_pl <- as_tibble(comparison_data) %>%
  mutate(avg.dist = as.factor(comparison_data$avg.dist), origin = as.factor(comparison_data$origin)) %>% 
  ggplot(aes(x = avg.dist, y = expr)) +
    geom_point(aes(color = origin), size = 1, alpha = 0) +
    geom_boxplot(aes(color = origin), width = 0.3, outlier.shape = NA) +  # Add boxplot
    geom_smooth(aes(color = origin, x = as.numeric(avg.dist), y = expr), method = 'lm', formula = y ~ ns(x, df = df), se = FALSE, linewidth = 0.5) +
    # geom_errorbar(aes(ymin = lower, ymax = upper, color = origin), width = 0.8, alpha = 0.5) +
    scale_color_manual(values = c("inside" = "black", "outside" = "lightgrey"), labels = c("inside" = "pixels in neighborhood", "outside" = "All other pixels")) +
    scale_x_discrete(breaks = unique(comparison_data$avg.dist)) +  # Show all x values
    scale_y_continuous(limits = c(y_min, y_max), expand = expansion(add = y_expansion)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression (log transformed)",
         subtitle = paste0(gene_of_interest, " expr. vs. Dist to endothelial cell annot. by ", marker.sel, " - bootstrapped ", stat))  +
    theme(plot.subtitle = element_text(size = 7)) +
    annotate("text", x = Inf, y = Inf, label = glue("P.Val = {P.Val}"), 
             hjust = 1.1, vjust = 1.5, size = 3) + 
    guides(color = guide_legend(override.aes = list(linetype = 1, size = 2)))  # Set legend as lines

# Save the plot with rectangular dimensions
expr_comparison_pl
```

```{r}
filename <- paste0("correlation plot of dists - bootstrap mean",  ".svg")
ggsave(filename = file.path(res.dir, "plots", filename), plot = expr_comparison_pl, device = "svg", width = 10, height = 8, dpi = 700)
```

```{r}
expr_comparison_violin <- comparison_data %>%
  mutate(dist.cluster = ordered(dist.cluster, levels = levels(fit$colData$dist.cluster))) %>% 
  ggplot(aes(x = dist.cluster, y = expr)) +
    geom_violin(aes(fill = origin), trim = F) +
    scale_fill_manual(values = c("inside" = "black", "outside" = "lightgrey"), labels = c("inside" = "pixels in neighborhood", "outside" = "All other pixels")) +
    scale_y_continuous(limits = c(y_min, y_max), expand = expansion(add = y_expansion)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression (log transformed)",
         subtitle = paste0(gene_of_interest, " expr. vs. Dist to endothelial cell - bootstrapped mean"))  +
    theme(plot.subtitle = element_text(size = 7))

expr_comparison_violin

filename <- paste0("expr_comparison_violin",  ".png")
ggsave(filename = file.path(res.dir, "plots", filename), plot = expr_comparison_violin, device = "png", width = 10, height = 8, dpi = 700)
```

```{r}
expr_comparison_scatter <- comparison_data %>%
  mutate(dist.cluster = ordered(dist.cluster, levels = levels(fit$colData$dist.cluster))) %>% 
  ggplot(aes(x = dist.cluster, y = expr)) +
    geom_point(aes(color = origin), size = 1) +
    # geom_smooth(aes(color = origin, x = as.integer(dist.cluster)), span = 1.5, spe = FALSE, linewidth = 2) +
    scale_color_manual(values = c("inside" = "black", "outside" = "lightgrey"), labels = c("inside" = "pixels in neighborhood", "outside" = "All other pixels")) +
    scale_y_continuous(expand = expansion(add = 0)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression",
         subtitle = paste0(gene_of_interest, " expr. vs. Dist to endothelial cell"))  +
    theme(plot.subtitle = element_text(size = 7))

expr_comparison_scatter
```

```{r}
filename <- paste0("correlation plot of dists_scatter",  ".png")
ggsave(filename = file.path(res.dir, "plots", filename), plot = expr_comparison_scatter, device = "png", width = 10, height = 8, dpi = 500)
```

```{r, paged.print=FALSE}
gene_of_interest
is_inside <- tibble(symbol = gene_of_interest, cell_id = list(colnames(fit))) %>%
  left_join(dplyr::select(nei, name, neighborhood), by = c("symbol"= "name")) %>%
  mutate(inside = map2(cell_id, neighborhood, \(ref, nei_pixels) ref %in% nei_pixels)) %>%
  dplyr::select(-neighborhood) %>%
  unnest(c(inside, cell_id))

```

```{r}
qs::qsave(is_inside, file.path(res.dir, "is_inside.qs"))

```

## UMAP DE

```{r}
# predicted DE
de_plot_data <- as_tibble(colData(fit), rownames = "cell_id") %>%
  mutate(umap = umap[colnames(fit),]) %>%
  mutate(de = as_tibble(t(assay(fit[gene_of_interest,], "DE")))) %>%
  unnest(de, names_sep = "-") %>%
  pivot_longer(starts_with("de-"), names_sep = "-", values_to = "de", names_to = c(NA, "symbol")) %>%
  inner_join(is_inside, by = c("symbol", "cell_id")) %>%
  sample_frac(size = 1)

abs_max <- max(abs(quantile(de_plot_data$de, c(0.95, 0.05))))

dist_de_pl <- de_plot_data %>%
  mutate(inside = ifelse(inside, "in", "out")) %>%
  mutate(inside = factor(inside, levels = c("in", "out")))  %>%
  ggplot(aes(x = umap[,2], y = umap[,1])) +
    ggrastr::rasterise(geom_point(aes(color = de), size = 0.5, stroke = 0), dpi = 600) +
    # scale_colour_gradient2_rev(limits = c(-1, 1) * abs_max, oob = scales::squish, breaks = c(-1, 0, 1) * signif_to_zero(abs_max, 1), mid = "lightgrey") +
    scale_color_de_gradient(abs_max, mid_width = 0.2) +
    facet_grid(vars(inside), labeller = labeller(inside = as_labeller(c("in" = "pixels in Neighb.", "out" = "All other pixels"))),
               switch="y") +
    small_axis("", fontsize = font_size_small) +
    theme(legend.position = "bottom", legend.margin = margin(t = -2, unit = "mm")) +
    guides(color = guide_colorbar(barheight = unit(1, "mm"), barwidth = unit(15, "mm"), title.vjust = 1)) +
    labs(color = "$\\Delta$")

dist_de_pl
```

```{r}
# filename <- paste0("UMAP_DE",  ".png")
# ggsave(filename = file.path(res.dir, "plots", filename), plot = dist_de_pl, device = "png", width = 10, height = 14, dpi = 800)
```

```{r, paged.print=FALSE}
# calculate the frac inside origin group!!
rel_plt <- colData(fit) %>%
  as_tibble(rownames = "cell_id") %>%
  left_join(is_inside) %>%
  dplyr::count(dist.cluster, symbol, inside) %>%
  mutate(frac = n / sum(n), .by = c(symbol, inside)) %>%  # calculate the frac inside origin group!!
  mutate(dist.cluster = fct_relabel(dist.cluster, \(x) str_replace(x, ",", ", "))) %>%
  ggplot(aes(x = dist.cluster, y = frac)) +
    geom_col(aes(fill = inside), position = position_dodge2()) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    scale_x_discrete(position = "top") +
    scale_fill_manual(values = c("TRUE" = "black", "FALSE" = "lightgrey")) +
    guides(x = guide_axis(angle = 90)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Rel. No. pixels - Group-Wise Fractions")

rel_plt 

# calculate the frac overall: divide by total amount of spots
rel_plt_2 <- colData(fit) %>%
  as_tibble(rownames = "cell_id") %>%
  left_join(is_inside) %>%
  dplyr::count(dist.cluster, symbol, inside) %>%
  mutate(total_n = sum(n), .by = symbol) %>%  # Calculate total count per symbol
  mutate(frac = n / total_n, .by = c(symbol, inside)) %>%  # calculate the frac inside origin group!!
  mutate(dist.cluster = fct_relabel(dist.cluster, \(x) str_replace(x, ",", ", "))) %>%
  ggplot(aes(x = dist.cluster, y = frac)) +
    geom_col(aes(fill = inside), position = position_dodge2()) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    scale_x_discrete(position = "top") +
    scale_fill_manual(values = c("TRUE" = "black", "FALSE" = "lightgrey")) +
    guides(x = guide_axis(angle = 90)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Rel. No. pixels - Overall Fractions")

rel_plt_2
```

#### Plot ECs and neighborhood

```{r}
gene_of_interest
method <- paste0("Manually by marker ", marker.sel)

# indicate if a spot is inside the neighborhood
inside <- rep("excluded", ncol(spe))
names(inside) <- colnames(spe)
nei_id <- is_inside %>% 
  filter(inside == TRUE) %>% 
  pull(cell_id)

nonnei_id <- is_inside %>% 
  filter(inside == FALSE) %>% 
  pull(cell_id)

inside[nei_id] <- "nei"
inside[nonnei_id] <- "non-nei"
inside.factor <- factor(inside, levels = c("nei", "non-nei", "excluded"))
specified_colors <- c("nei" = "blue", "non-nei" = "lightblue", "excluded" = "lightgrey")

info_of_interest <- "neibourhood spots"
cluster <- target.cell
  
groups <- rep("others", ncol(spe))
groups[unlist(is.ec.spot)] <- cluster

strokes <- ifelse(groups == cluster, 0.5, 0)

# Create ggplot object
plots_ECs_nei <- as_tibble(spatialCoords(spe)) %>%
  mutate(groups = groups, strokes = strokes, inside.col = inside.factor) %>%
  ggplot(aes(x = x, y = y)) +
  geom_point(aes(stroke = strokes, shape = groups, fill = inside.col), size = 2, alpha = 0.5, color = "black") + # here is the border color
  scale_shape_manual(values = c(24, 21)) +
  scale_fill_manual(values = specified_colors) +
  labs(title = glue("{info_of_interest}  vs ECs from {method} for gene: {gene_of_interest}"),
       x = "pxl_row_in_fullres",
       y = "pxl_col_in_fullres",
       fill = "spots category by color",
       shape = "cell type group by shape") + 
  guides(fill = guide_legend(override.aes = list(shape = 22,
                                                color = c("blue", "lightblue", "lightgrey")))) 

filename <- paste0(info_of_interest, " vs ", "ECs from ", method,  ".svg")
ggsave(filename = file.path(res.dir, "plots", filename), plot = plots_ECs_nei, device = "svg", width = 10, height = 8)

filename <- glue("ECs and nei - {gene_of_interest}.png")

ggsave(filename = file.path(res.dir, "plots", filename), plot = plots_ECs_nei, device = "png", width = 10, height = 8, dpi = 500, bg = "white")

plots_ECs_nei
```

## Save plot

```{r}
plot <- expr_comparison_pl / expr_comparison_violin / rel_plt_2
filename <- glue("coorelation plot - {gene_of_interest}.png")
ggsave(filename = file.path(res.dir, "plots", filename), plot = plot, device = "png", width = 10, height = 14, dpi = 800,   bg = "white" # Set background to white
)

plot
```

```{r}
# plot <- expr_comparison_original_mean_pl /rel_plt_2
# filename <- paste0("expr_comparison_original_mean_pl",  ".png")
# ggsave(filename = file.path(res.dir, "plots", filename), plot = plot, device = "png", width = 10, height = 14, dpi = 800)
# 
# plot
```

```{r}
# plot <- expr_comparison_original_mean_pl /rel_plt_2
# filename <- paste0("expr_comparison_original_mean_pl",  ".png")
# ggsave(filename = file.path(res.dir, "plots", filename), plot = plot, device = "png", width = 10, height = 14, dpi = 800)
# 
# plot
```

## Misc.

```{r}
library(ggplot2)
library(gghighlight)

# Sample data
data <- data.frame(
  x = rnorm(100),
  y = rnorm(100),
  group1 = sample(c("A", "B"), 100, replace = TRUE),  # First group
  group2 = sample(c("X", "Y", "Z"), 100, replace = TRUE)  # Second group
)

# Create the plot with gghighlight
ggplot(data, aes(x = x, y = y, shape = group1, fill = group2)) +
  geom_point(size = 4, stroke = 1.5, color = "black") +  # Adjust point size and outline color
  scale_shape_manual(values = c(21, 22)) +  # Shapes for group1
  scale_fill_manual(values = c("red", "blue", "green")) +  # Fill colors for group2
  gghighlight(group2 == "Y",  # Highlight points where group2 is "Y"
              use_direct_label = FALSE, 
              label_key = group2,
              unhighlighted_params = list(alpha = 0.3)) +  # Adjust transparency of unhighlighted points
  theme_minimal() +
  labs(title = "Scatter Plot with Highlights",
       x = "X-axis Label",
       y = "Y-axis Label",
       shape = "Group 1",
       fill = "Group 2")

```
