---
title: "R Notebook"
---


```{r}
library(tidyverse)
library(glue)
library(SingleCellExperiment)
library(lemur)
source("util.R")
```




```{r}
fit <- qs::qread("../benchmark/output/cable_spatial_plaque_data/fit_small.qs")
nei <- qs::qread("../benchmark/output/cable_spatial_plaque_data/nei_small.qs")
```



```{r}
mouse_labels <- structure(paste0("Mouse ", 1:4), names = paste0("mouse_", 1:4))
```



```{r, paged.print=FALSE}
spatial_plaq_dens_pl <- as_tibble(colData(fit)) %>%
  ggplot(aes(x = x, y = y)) +
    ggrastr::rasterize(geom_point(aes(color = plaque_density), size = 0.05, stroke = 0), dpi = 600) +
    scale_color_gradient(low = "lightgrey", high = "darkorange", limits = c(0, 1), breaks = c(0, 0.5, 1)) +
    facet_wrap(vars(sample), labeller = as_labeller(mouse_labels)) +
    small_axis(label = "spatial coord.", fontsize = font_size_small) +
    labs(color = "Plaque density", subtitle = "Spatial structure") +
    guides(color = guide_colorbar(barheight = unit(1, "mm"))) +
    theme(legend.position = "top", strip.text = element_text(size = font_size_tiny, margin = margin(b = -1, unit = "mm")),
          plot.subtitle = element_text(size = 7))

spatial_plaq_dens_pl
```


```{r}
set.seed(1)
umap <- uwot::umap(t(fit$embedding))
```


```{r}
as_tibble(colData(fit)) %>%
  mutate(umap = umap) %>%
  ggplot(aes(x = umap[,1], y = umap[,2])) +
    geom_point(aes(color = sample), size = 0.3, stroke = 0) +
    guides(color = guide_legend(override.aes = list(size = 1)))

as_tibble(colData(fit)) %>%
  mutate(umap = umap) %>%
  ggplot(aes(x = umap[,1], y = umap[,2])) +
    geom_point(aes(color = cell_type_lumped), size = 0.3, stroke = 0) +
    guides(color = guide_legend(override.aes = list(size = 1)))

as_tibble(colData(fit)) %>%
  mutate(umap = umap) %>%
  ggplot(aes(x = umap[,1], y = umap[,2])) +
    geom_point(aes(color = plaque_cluster), size = 0.3, stroke = 0) +
    guides(color = guide_legend(override.aes = list(size = 1)))
```

```{r}
umap_plt <- as_tibble(colData(fit)) %>%
  mutate(umap = umap) %>%
  ggplot(aes(x = umap[,2], y = umap[,1])) +
    ggrastr::rasterize(geom_point(aes(color = plaque_density), size = 0.1, stroke = 0, show.legend = FALSE), dpi = 600) +
    scale_color_gradient(low = "lightgrey", high = "darkorange", limits = c(0, 1), breaks = c(0, 0.5, 1))  +
    small_axis(label = "UMAP", fontsize = font_size_small) +
    labs(subtitle = "Latent structure") +
    theme(plot.subtitle = element_text(size = 7))

umap_plt
```

Make cell type plot

```{r}
table(fit$colData$cell_type_lumped, fit$colData$cell_type, useNA = "always")
```


```{r, paged.print=FALSE}
celltype_broad_plt <- as_tibble(colData(fit)) %>%
  mutate(umap = umap) %>%
  ggplot(aes(x = umap[,2], y = umap[,1])) +
    ggrastr::rasterize(geom_point(aes(color = cell_type_lumped), size = 0.1, stroke = 0, show.legend = FALSE), dpi = 600) +
    ggrepel::geom_label_repel(data = . %>% summarize(umap = matrix(colMedians(umap), nrow = 1), .by = cell_type_lumped), 
                              aes(label = cell_type_lumped, color = cell_type_lumped), size = font_size_small / .pt, show.legend = FALSE, max.overlaps = 100) +
    scale_x_continuous(limits = range(umap[,2]) * 1.5) +
    small_axis(label = "UMAP", fontsize = font_size_small) +
    labs(title = "(B) Mouse hypocampus: broad cell type labels") 
```

```{r}
cowplot::save_plot("../plots/suppl_alzheimer_cell_types.pdf", celltype_broad_plt, base_height = 8, base_width = 8, units = "cm")
```



```{r, paged.print=FALSE}
genes_of_interest <- nei$name[1]
mask <- matrix(NA, nrow = length(genes_of_interest), ncol = ncol(fit), 
               dimnames = list(genes_of_interest, colnames(fit)))
mask2 <- matrix(1, nrow = length(genes_of_interest), ncol = ncol(fit), 
               dimnames = list(genes_of_interest, colnames(fit)))
for(id in genes_of_interest){
  mask[id, filter(nei, name == id)$neighborhood[[1]]] <- 1
  mask2[id, filter(nei, name == id)$neighborhood[[1]]] <- NA
}

psce2 <- glmGamPoi::pseudobulk(SingleCellExperiment(list(inside = as.matrix(logcounts(fit)[genes_of_interest,,drop=FALSE] * mask),
                                                        outside = as.matrix(logcounts(fit)[genes_of_interest,,drop=FALSE] * mask2))),
                      group_by = vars(sample, plaque_cluster), n = n(),
                      aggregation_functions = list(.default = \(...) matrixStats::rowMeans2(..., na.rm = TRUE)),
                      col_data = as.data.frame(colData(fit)))

comparison_data <- as_tibble(colData(psce2)) %>%
  mutate(expr_inside = as_tibble(t(assay(psce2, "inside"))),
         expr_outside = as_tibble(t(assay(psce2, "outside")))) %>%
  unpack(starts_with("expr"), names_sep = "-") %>%
  pivot_longer(starts_with("expr"), names_sep = "[-_]", names_to = c(".value", "origin", "symbol")) 



expr_comparison_pl <- comparison_data %>%
  mutate(plaque_cluster = ordered(plaque_cluster, levels = levels(fit$colData$plaque_cluster))) %>% 
  ggplot(aes(x = plaque_cluster, y = expr)) +
    geom_point(aes(color = origin), size = 0.3) +
    geom_smooth(aes(color = origin, x = as.integer(plaque_cluster)), span = 1.5, se = FALSE, linewidth = 2) +
    scale_color_manual(values = c("inside" = "black", "outside" = "lightgrey"), labels = c("inside" = "Cells in neighborhood", "outside" = "All other cells")) +
    scale_y_continuous(limits = c(0, 0.3), expand = expansion(add = 0)) +
    guides(x = guide_axis(angle = 45)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Expression",
         subtitle = "\\emph{Jun} expr. vs. plaque density")  +
    theme(plot.subtitle = element_text(size = 7))

expr_comparison_pl
```


```{r, paged.print=FALSE}
is_inside <- tibble(symbol = genes_of_interest, cell_id = list(colnames(fit))) %>%
  left_join(dplyr::select(nei, name, neighborhood), by = c("symbol"= "name")) %>%
  mutate(inside = map2(cell_id, neighborhood, \(ref, nei_cells) ref %in% nei_cells)) %>%
  dplyr::select(-neighborhood) %>%
  unnest(c(inside, cell_id))

de_plot_data <- as_tibble(colData(fit), rownames = "cell_id") %>%
  mutate(umap = umap) %>%
  mutate(de = as_tibble(t(assay(fit[genes_of_interest,], "DE")))) %>%
  unnest(de, names_sep = "-") %>%
  pivot_longer(starts_with("de-"), names_sep = "-", values_to = "de", names_to = c(NA, "symbol")) %>%
  inner_join(is_inside, by = c("symbol", "cell_id")) %>%
  sample_frac(size = 1) 

abs_max <- max(abs(quantile(de_plot_data$de, c(0.95, 0.05))))

jun_de_pl <- de_plot_data %>%
  mutate(inside = ifelse(inside, "in", "out")) %>%
  mutate(inside = factor(inside, levels = c("in", "out")))  %>%
  ggplot(aes(x = umap[,2], y = umap[,1])) +
    ggrastr::rasterise(geom_point(aes(color = de), size = 0.05, stroke = 0), dpi = 600) +
    # scale_colour_gradient2_rev(limits = c(-1, 1) * abs_max, oob = scales::squish, breaks = c(-1, 0, 1) * signif_to_zero(abs_max, 1), mid = "lightgrey") +
    scale_color_de_gradient(abs_max, mid_width = 0.2) +
    facet_grid(vars(inside), labeller = labeller(inside = as_labeller(c("in" = "Cells in Neighb.", "out" = "All other cells"))),
               switch="y") +
    small_axis("", fontsize = font_size_small) +
    theme(legend.position = "bottom", legend.margin = margin(t = -2, unit = "mm")) +
    guides(color = guide_colorbar(barheight = unit(1, "mm"), barwidth = unit(15, "mm"), title.vjust = 1)) +
    labs(color = "$\\Delta$")

jun_de_pl
```





```{r, paged.print=FALSE}
rel_plt <- colData(fit) %>%
  as_tibble(rownames = "cell_id") %>%
  left_join(is_inside) %>%
  dplyr::count(plaque_cluster, symbol, inside) %>%
  mutate(frac = n / sum(n), .by = c(symbol, inside)) %>%
  mutate(plaque_cluster = fct_relabel(plaque_cluster, \(x) str_replace(x, ",", ", "))) %>%
  ggplot(aes(x = plaque_cluster, y = frac)) +
    geom_col(aes(fill = inside), position = position_dodge2()) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    scale_x_discrete(position = "top") +
    scale_fill_manual(values = c("TRUE" = "black", "FALSE" = "lightgrey")) +
    guides(x = guide_axis(angle = 90)) +
    theme(axis.title.x = element_blank(), legend.position = "bottom") +
    labs(color = "", y = "Rel. No. Cells")
rel_plt
```




```{r}
plot_assemble(
  add_text("(D) Alzheimer plaque density", x = 2.7, y = 1, fontsize = font_size, vjust = 1, fontface = "bold"),
  add_plot(cowplot::get_legend(spatial_plaq_dens_pl + theme(legend.text = element_text(size = font_size)) + labs(color = "")), x = 43, y = 1, height = 5),
  add_plot(spatial_plaq_dens_pl + guides(color = "none"), x = 0, y = 5, width = 60, height = 61),
  add_plot(umap_plt, x = 52, y = 5, width = 40, height = 61),
  add_text("(E) \\emph{Jun} expression depends on the plaque density\n\\quad\\quad{}in a subset of cells",
           x = 95, y = 1, fontsize = font_size, vjust = 1, fontface = "bold"),
  add_text("Pred.~\\emph{Jun} diff.~expr.",
           x = 97.5, y = 8, fontsize = 7, vjust = 1, fontface = "plain"),
  add_text("UMAP", x = 102.3, y = 58, fontsize = font_size_small, fontface = "plain"),
  add_plot(jun_de_pl, x = 95, y = 4.5, width = 25, height = 61.5),
  add_plot(expr_comparison_pl + guides(color = "none") + theme(axis.text.x = element_blank()), x = 120, y = 6.7, width = 50, height = 28.8),
  add_plot(rel_plt + guides(fill = "none"), x = 120, y = 34, width = 50, height = 26),
  add_plot(cowplot::get_legend(expr_comparison_pl), x = 125, y = 60, width = 60, height = 5),
  
  add_graphic("../plots/schematic_elements/alzheimer_circle.pdf", x = -1,  y = -1, units = "mm"),
  
  width = 170, height = 65, units = "mm", show_grid_lines = FALSE,
  latex_support = TRUE, filename = "../plots/continuous_covar_figure_part2.pdf"
)

```
